### ISSUE TITLE
Highlighted features shifts when resizing map

### ISSUE THREAD

**Issue by liriarte** [mapgears/ol3-google-maps#101]
I am trying to highlight some features from a layer (ol.source.TileWMS) after drawing a box. I have found the following problem:

*) I can highlight the features (using ol.interaction.Select and pushing the selected features) but the selection does not refresh/sync/move when the map is resized (see attached screenshots, there are 2 dots highlighted in blue), and therefore ends up in the wrong place (shifted)

![screen shot 2016-07-08 at 17 05 39](https://cloud.githubusercontent.com/assets/9697144/16693698/50495902-452e-11e6-825a-8b6523e45184.png)
![screen shot 2016-07-08 at 17 05 53](https://cloud.githubusercontent.com/assets/9697144/16693697/5046d754-452e-11e6-9e7b-4af9d9dac7a5.png)

Please help.

**Comment by alexbrault** [comment]
Off the top of my head, I think this might be caused by the select interaction's unmanaged layer. I don't think the heralds currently look for those

**Comment by samuellapointe** [comment]
Could you create a jsfiddle demonstrating the issue? It would make it easier to find the source of the problem. You could use [this template](http://jsfiddle.net/g40cahh3/3/)

**Comment by liriarte** [comment]
I may need some time be able to create a similar example online. In the meantime I created the following jsfiddle: http://jsfiddle.net/liriarte/g40cahh3/9/

Shouldn't the map update its size and take the whole width when the div is toogled?

**Comment by samuellapointe** [comment]
In your fiddle, the map is set to take 92% of the width. It will take that amount of space even if the sidebar is removed. I updated the CSS to act like a table so that it fills the space when available: http://jsfiddle.net/q8s1Lf54/

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
