### ISSUE TITLE
Google map Hybrid

### ISSUE THREAD

**Issue by luanpcweb** [mapgears/ol3-google-maps#107]
It can show in hybrid mode?
P.S. Thanks for the good job.

**Comment by adube** [comment]
Hello.  Thanks for your interest in the library.

Would you please be more specific?  What do you mean by hybrid mode?

**Comment by Orion3090** [comment]
I know this is old, but isn't there anything on this topic?
EDIT: The answer is yes, it does, youst create the layer like this:
`var googleLayer = new olgm.layer.Google({ mapTypeId: google.maps.MapTypeId.HYBRID });`

hope it helps someone!

**Comment by adube** [comment]
Thanks @Orion3090
