### ISSUE TITLE
Overview map example doesn't work when compiled

### ISSUE THREAD

**Issue by samuellapointe** [mapgears/ol3-google-maps#117]
When using the compiled library, the overview example doesn't work. I get the following error from the Google Maps API:

```
Uncaught TypeError: Cannot read property '__e3_' of undefined
```

I will remove it from the website until we find a fix.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
