### ISSUE TITLE
Cluster Issue

### ISSUE THREAD

**Issue by studentitm** [mapgears/ol3-google-maps#12]
Thanks for making such a useful library.

I am trying the Openlayers 3 clustering example using this library in Google Maps.

While styling the clusters, i printed the feature object .
It prints 3 times.For first time it comes out to be undefined but right in the next two times.
This causes the following error in line (  var size = feature.get('features').length; )

Uncaught TypeError: Cannot read property 'get' of undefined

Due to this, the clusters are drawn on map but the code after clusters does not execute.

style: function(feature, resolution) {
console.log(feature);
    var size = feature.get('features').length;
    var style = styleCache[size];
    if (!style) {
      style = [new ol.style.Style({
        image: new ol.style.Circle({
          radius: 10,
          stroke: new ol.style.Stroke({
            color: '#fff'
          }),
          fill: new ol.style.Fill({
            color: '#3399CC'
          })
        }),
        text: new ol.style.Text({
          text: size.toString(),
          fill: new ol.style.Fill({
            color: '#fff'
          })
        })
      })];
      styleCache[size] = style;
    }
    return style;
  }

It works fine without the library.

Also, upto what time will you support images as markers.
I plotted marker images on map but they are not hidden when i switch them off from layer switcher.

**Comment by adube** [comment]
Thanks for reporting this.  There may be two reasons for this:
- style functions haven't been tested yet, i.e. they are not supported at the moment.  A style has to be defined as an object for the library to be able to read it and convert it into a Google Maps style
- clusters have not been tested either yet, but that's something that could be interesting.

If you're willing to work on a PR, I'd be happy to review.

To answer your last question: image as markers are supported.  See an example: http://dev5.mapgears.com/ol3-google-maps/examples/vector.html.  Again, make sure to define a style object, not a style function.

I'll adjust the LIMITATION.md file to reflect these limitations.

**Comment by adube** [comment]
For the record, this documentation page from Google Maps API would be a good start for the integration of clusters within this library: https://developers.google.com/maps/articles/toomanymarkers?hl=en

**Comment by studentitm** [comment]
Thanks a lot for the answer.
I will try defining cluster style as object.

In case of image markers, they do work.But i could not hide the layer using vector.setVisible(false) function.

**Comment by adube** [comment]
@studentitm, I understand now.  This is a bug.  I reported this in a separate issue: #13.

**Comment by adube** [comment]
I moved the task of supporting clusters in an other ticket: #52.  I'm closing this one.

**Comment by ibrahimnegm2011** [comment]
Is this issue solved or not .. I need to show the number of the features in the cluster icon .. is there is any other solutions for that ?

**Comment by adube** [comment]
Clusters are not supported yet.  Please, use #52 to continue this discussion.
