### ISSUE TITLE
WMTS Layer from Capabilities

### ISSUE THREAD

**Issue by luciman** [mapgears/ol3-google-maps#120]
Hi
I use a wmts layer from capabilities like in openlayers example 
http://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html

Is there a limitation in ol3gm or a do something wrong?
http://jsfiddle.net/s1hth79u/1/

If osmLayer is toggled wmts layer works but with google layer don't.

Thanks

**Comment by adube** [comment]
I'm not sure what's wrong.  WMTS should be supported: http://mapgears.github.io/ol3-google-maps/examples/dist/examples/wmts.html

I'll try to debug that this week in an attempt to understand what's going wrong.

**Comment by luciman** [comment]
On that example it works, but if I insert the layer direct from wmts capabilities like in ol example it doesn't work. I saw in firebug the requests and I observe the tile grid of the requests is wrong.

**Comment by adube** [comment]
The reason it's not working is explained in the limitations, see here: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#custom-tilegrid-with-ollayertile

I tried to make your example working and I did by forcing my own tile grid:

```
  var options = ol.source.WMTS.optionsFromCapabilities(result,
    {layer: 'layer-7328', matrixSet: 'EPSG:3857'});

    var projection = ol.proj.get('EPSG:3857');
    var projectionExtent = projection.getExtent();

    var size = ol.extent.getWidth(projectionExtent) / 256;
    var resolutions = new Array(14);
    var matrixIds = new Array(14);
    for (var z = 0; z < 14; ++z) {
      // generate resolutions and matrixIds arrays for this WMTS
      resolutions[z] = size / Math.pow(2, z);
      matrixIds[z] = z;
    }

    options.tileGrid = new ol.tilegrid.WMTS({
      origin: ol.extent.getTopLeft(projectionExtent),
      resolutions: resolutions,
      matrixIds: matrixIds
    });
```

HTH

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
