### ISSUE TITLE
Vector Layer Z index not working properly

### ISSUE THREAD

**Issue by JohnWick1234** [mapgears/ol3-google-maps#121]
Hi! OpenLayers 3 with ol3-google-maps,  Zindex is setting but visibly the layer is not rendering based on this zindex over google map.

With reference to http://openlayers.org/en/v3.9.0/examples/layer-z-index.html

**Comment by adube** [comment]
You're right.  That has not been taken into account, yet.  If you're willing to work on a PR, I'd be happy to review it.  Otherwise, we could add this as a limitation (for now).

Thanks for your interest in ol3-google-maps!

**Comment by guyBy** [comment]
zIndex still not working with ol3-google-maps.
Is there any workaround to control features layers ordering?
Thanks

**Comment by adube** [comment]
Not that I'm aware of, as this feature has not been implemented in ol3-google-maps.

Don't hesitate to contribute a patch.  I'd be happy to review it.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
