### ISSUE TITLE
When I use "useCanvas: true" I get Error

### ISSUE THREAD

**Issue by IsmayilAqazade** [mapgears/ol3-google-maps#123]
![ol3gm1](https://cloud.githubusercontent.com/assets/5353956/17977650/987a32dc-6b03-11e6-942f-6368f409d27c.png)

Hi.When I use useCanvas: true I get this Error:

![ol3gm2](https://cloud.githubusercontent.com/assets/5353956/17977668/a84ffd0e-6b03-11e6-8208-eecb37895980.png)

**Comment by samuellapointe** [comment]
This sounds a lot like a bug we fixed this morning... Can you try with the latest release, 0.10.2?

**Comment by IsmayilAqazade** [comment]
@samuellapointe Thank, the error is solved in 0.10.2. However, I get another error now. The icons are not shown on map, when the page is refreshed.

**Comment by IsmayilAqazade** [comment]
It's not pretty code ,but solved the problem:
window.setTimeout(function() {olGM.activate();
        sip.geo.zoomToCoordinate( Number(sip.model.business.getLongitude()),Number(sip.model.business.getLatitude()));
    }, 2000);

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
