### ISSUE TITLE
Google Maps Directions AP

### ISSUE THREAD

**Issue by wackari** [mapgears/ol3-google-maps#126]
Hi can we use Google Maps Directions API?  o.O?

Thanks and regards

**Comment by adube** [comment]
Yes, you can.  You simply need to fetch the Google Maps map object from OLGM then do what you want with it.

In this example, a Google traffic layer is added: http://mapgears.github.io/ol3-google-maps/examples/dist/examples/traffic.html

```
var gmap = olGM.getGoogleMapsMap();

var trafficLayer = new google.maps.TrafficLayer();
trafficLayer.setMap(gmap);
```

Please, let us know if that answers your question.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
