### ISSUE TITLE
Google Maps data not following OL3 layer visibility

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#13]
Currently, when an OL3 vector layer visibility is unset, the data in Google Maps is still being shown.

**Comment by studentitm** [comment]
Thanks @adube

**Comment by adube** [comment]
@studentitm, would you please see if #14 fixes the issue for you ?

**Comment by studentitm** [comment]
Thanks for the fix @adube .

**Comment by adube** [comment]
You're quite welcome.  Thank you for reporting this.
