### ISSUE TITLE
ol3-google-maps with ol3-cesium

### ISSUE THREAD

**Issue by mike4009** [mapgears/ol3-google-maps#133]
Hi 

Can we use OL3-Cesium library with this library? My current project uses Openlayers3 and OL3-Cesium but I need a Google Satellite imagery for my map/globe. I'm having an error when I replaced my Openlayers3 library with Ol3gm.

Thanks and regard,

**Comment by adube** [comment]
Hello Mike.

At this moment, ol3-google-maps is not compatible with ol3-cesium because of the way Google Maps is added.  It's would not be 'impossible', but would require development enable this.

If you're interested in working on this or funding this, we could discuss this more.  Please, let us know.

**Comment by hspain** [comment]
Has there been any development along these lines?  I am also looking to use these two libraries together.

**Comment by adube** [comment]
No development has been made so far.  Contributions would be appreciated.

**Comment by hspain** [comment]
I would love to contribute here.  Any chance I can get a bit of insight as to where in the codebase I should focus?

**Comment by adube** [comment]
The library by itself is that big.  Its main component is the OLGoogleMaps class, which describes (in the class description) what is the basic idea behind OLGM:

https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/OLGoogleMaps.js

You'll see what heralds are and what they do.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
