### ISSUE TITLE
disappearing circle features

### ISSUE THREAD

**Issue by glchua2** [mapgears/ol3-google-maps#134]
I notice a weird behavior when playing around with [concept example](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/concept.html).

With google map as base layer, i tried zooming in 3 times to a spot with no features ( e.g winnipeg )  followed by panning around the map quickly for a few times. After that, I zoom out a few times and notice that some/all of the circle features have disappeared. 

After this occurred, sometimes changing the zoom level will bring back some of the features (but may not always occur). Below is a screenshot of the aftermath:
![ss](https://cloud.githubusercontent.com/assets/2323076/19722952/8eb3e454-9bab-11e6-88de-4abd4f06c3fa.png)

This scenario does not happen when i am using OSM map as base layer though.

**Comment by adube** [comment]
Thanks for reporting this.

**Comment by glchua2** [comment]
Just to add on further observation, hiding google map layer will bring back the disappearing circle feature. Based on my experimentation, features are not re-rendered when setting visibility of map layer, so i don't think that it is a rendering issue.

Tinkering with zIndex does not solve the issue too. Any idea what is causing this?

**Comment by adube** [comment]
FYI, hiding the Google Maps' map makes OL3 render the features back.  When a gmaps layer is on, olgm takes care of rendering the features using its herald objects.

I checked how the style objects are created and I couldn't find any problem there:

https://github.com/mapgears/ol3-google-maps/blob/v0.11.2/src/gm/gm.js#L135-L312

The problem appears at a moment that I can't currently identify why / how.  Any PR with a patch would be appreciated.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
