### ISSUE TITLE
MULTIPOLYGON isn't supported... Help me!

### ISSUE THREAD

**Issue by jose1914luis** [mapgears/ol3-google-maps#135]
the MULTIPOLYGON shape isn't implemented, this is a powerful functionality in OpenLayer 2. is necessary convert the shape from ol3 to google map, I don't know how put this. I explain the problem in https://stackoverflow.com/questions/40243847/loading-multipolygon-in-openlayer-3-with-ol3-google-maps/

**Comment by adube** [comment]
I added a notification to the limitations: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#multi-geometries

**Comment by jacobo** [comment]
Hi, I'd like to help and contribute support for MultiPolygon

I'm pasting here's what I've got working so far:

    @@ -81489,7 +81489,8 @@ olgm.gm.createFeatureGeometry = function(geometry, opt_ol3map) {
       if (geometry instanceof ol.geom.Point) {
         gmapGeometry = olgm.gm.createLatLng(geometry, opt_ol3map);
       } else if (geometry instanceof ol.geom.LineString ||
    -             geometry instanceof ol.geom.Polygon) {
    +             geometry instanceof ol.geom.Polygon ||
    +             geometry instanceof ol.geom.MultiPolygon) {
         gmapGeometry = olgm.gm.createGeometry(geometry, opt_ol3map);
       }
 
    @@ -81533,26 +81534,34 @@ olgm.gm.createGeometry = function(geometry, opt_ol3map) {
       var inProj = (opt_ol3map !== undefined) ?
           opt_ol3map.getView().getProjection() : 'EPSG:3857';
 
    -  var latLngs = [];
    -  var lonLatCoords;
    +  // TODO: check repo for MultiPolygon PR
    +  var genLatLngs = function(coordinates){
    +    var latLngs = [];
    +    var lonLatCoords;
 
    -  var coordinates;
    -  if (geometry instanceof ol.geom.LineString) {
    -    coordinates = geometry.getCoordinates();
    -  } else {
    -    coordinates = geometry.getCoordinates()[0];
    -  }
    -
    -  for (var i = 0, len = coordinates.length; i < len; i++) {
    -    lonLatCoords = ol.proj.transform(coordinates[i], inProj, 'EPSG:4326');
    -    latLngs.push(new google.maps.LatLng(lonLatCoords[1], lonLatCoords[0]));
    +    for (var i = 0, len = coordinates.length; i < len; i++) {
    +      lonLatCoords = ol.proj.transform(coordinates[i], inProj, 'EPSG:4326');
    +      latLngs.push(new google.maps.LatLng(lonLatCoords[1], lonLatCoords[0]));
    +    }
    +    return latLngs;
       }
 
       var gmapGeometry = null;
    -  if (geometry instanceof ol.geom.LineString) {
    -    gmapGeometry = new google.maps.Data.LineString(latLngs);
    -  } else {
    -    gmapGeometry = new google.maps.Data.Polygon([latLngs]);
    +
    +  if (geometry instanceof ol.geom.MultiPolygon){
    +    var latLngsArr = []
    +    geometry.getCoordinates()[0].forEach(function(coordsArr){
    +      latLngsArr.push(genLatLngs(coordsArr));
    +    });
    +    gmapGeometry = new google.maps.Data.Polygon(latLngsArr);
    +  } else{
    +    if (geometry instanceof ol.geom.LineString) {
    +      var latLngs = genLatLngs(geometry.getCoordinates());
    +      gmapGeometry = new google.maps.Data.LineString(latLngs);
    +    } else {
    +      var latLngs = genLatLngs(geometry.getCoordinates()[0]);
    +      gmapGeometry = new google.maps.Data.Polygon([latLngs]);
    +    }
       }
 
       return gmapGeometry;


Now to fork the repo and try to do this the "Right way"...

**Comment by adube** [comment]
Multi polygons were implemented in #180
