### ISSUE TITLE
ol3gm v.0.8 - TypeError: this.set is not a function when using an API key by google

### ISSUE THREAD

**Issue by zorta86** [mapgears/ol3-google-maps#136]
I'm getting this error: 

> ol3gm.js:13 Uncaught TypeError: this.set is not a function(…)

 when I use a valid API key from google API console.

If I don't use the key, everything works fine.

But I want just to add some details: I'm actually using html2canvas to export PNG, and it works great. But if I use the API key the exported PNG works but it don't shows any marker.
If I DON'T use any API keys, the screenshot works and markers appear.

So, I'm doing something wrong with the key or is there an actual existing bug?

UPDATE: I noticed that if I use the "callback" defined after the "key" params in javascript declaration, I get the error. Without callback (and with the API key) it works great.
Example: `<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<myKey_xxxxxxx>&callback=__async_req_1__"></script>`

**Comment by adube** [comment]
Would you please create a small live example that demonstrates the issue you're having?  Also, try to use ol3gm-debug.js instead to see if you can debug the error yourself.

**Comment by adube** [comment]
Also, I'm not sure but exporting a Google Maps map may a violation of their terms of use, see:  https://developers.google.com/maps/terms, under 10.5 Intellectual Property Restrictions. section c.

**Comment by zorta86** [comment]
I'll create an example but first let me explain in details:
- I'm using requireJS to load google maps and other libs. It use "async" plugin for requireJS to load map (`https://github.com/millermedeiros/requirejs-plugins`)
- It load the maps correctly but, at some point, the ol3gm throw an exception (see first post). Why? Because the async use the callback param to load the map (see 2nd post)
- the map works correctly but that kind of error, for no reason, prevent the correct function of "html2canvas" plugin (and I need it)
- I can't find an example on how to use the callback param in gmap with ol3gm

**Comment by zorta86** [comment]
UPDATE: in debug version I have this:
- error at 105904, this.set is not a function `this.set('font', 'normal 10px sans-serif');`
- indeed, `typeof this: "object"`

If I don't use the callback param, `this` is a function and everything works fine (but I repeat: I need requireJS, and it use a callback param to init the gmap)

**Comment by zorta86** [comment]
UPDATE:

Error at 105904, the "set" function he need is the `_.m.set()` function defined inside `<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<myKey_xxxxxxx>&callback=__async_req_1__"></script>`.

I don't know why, but using a callback to load the map it prevents triggering the `_.m.set()`.
Actually I need a live example on how to use a callback to load gmaps with OL3GM. If this kind of loading is not provided by OL3GM, I can close here the post has solved (due to my specific implementation).

**Comment by adube** [comment]
Honestly, I don't know much about RequireJS nor what is the use of that callback method.  I'd be happy to see a fix to support this but my knowledge is limited for the moment.  If you're able to make it work by patching OL3GM, I'd be happy to review a PR.  An example would also be nice to demonstrate how this could be used.

I'd leave this ticket opened for future references and until a fix is made OR if at somepoint we figure out that it has nothing to do with OL3GM.

What do you think?

**Comment by zorta86** [comment]
I think this is the best we can do. And I have a semi-nice update! I solved my problem like this:
- using first RequireJS to load all the libs that don't depend on OL and OL3GM
- I created my main (for the first RequireJS) and added a timeout. This timeout just check if gmaps has been loaded (see below)
- I defined a custom script where I get the maps (with [jquery getScript](https://api.jquery.com/jquery.getscript/) ). Now, inside my custom "define" and within the "done" function of getScript, I re-instance RequireJS. Inside it, I call the OL and OL3GM libs (thats the "trick")
- in my main, where I put a timeout, I'm waiting for a global variable setted inside the second requireJS. If the variable is TRUE then my maps is loaded. If FALSE, still waiting.

For the moment, thats the best solution I can achieve and it works really nice!
But would be great if OL3GM could implements this kind of behavior.

**Comment by rawsonl** [comment]
I have this exact issue.  If I used the "callback" after the "key" params I get this error.  I would really like the ability to utilize a callback from the map.  That way I can ensure the map is loaded before doing any processing.

**Comment by adube** [comment]
Please, feel free to provide a patch.  It would also be nice to have a new example featuring how RequireJS can be used with OLGM, which would demonstrate the fix in action.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
