### ISSUE TITLE
Support rotateWithView

### ISSUE THREAD

**Issue by trinityzhub** [mapgears/ol3-google-maps#147]
feature.setStyle(new ol.style.Style({
     image: new ol.style.Icon( ({
     rotateWithView: true,
 rotation:datainRadians,   /// no rotate in ol3gm

It is working in ol3 but not in ol3gm

using latest ol3gm

**Comment by adube** [comment]
The `rotateWithView` is not currently supported within OL3-Google-Maps.  It would require development to be able to accomplish this.

A contribution would be welcome.

**Comment by trinityzhub** [comment]
I can rotate the feature while initialisation/Declaration.
But i can't rotate the feature after the initialisation.

IS THERE ANY  SOLUTION. 
----------------------------------------------------------------------------------------------
I tried:
1. Style Function  
2. feature.getStyle().getImage().setRotation(angle);  // set rotation
3. SetStyle                                                             // Set Whole Style


------------------------------------------------------------------------------------------------

**Comment by adube** [comment]
As previously mention, this is not currently supported.  It would require development.  Contributions are welcome.

Thanks for your interests.

**Comment by trinityzhub** [comment]
How can I contribute on this Enhancement?

**Comment by adube** [comment]
You need to fork the repository, clone it locally and install the development environment.  See: https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md

Then, you can create a branch to work on a patch.  Make sure you run `make lint` and `make dist` often as you develop.

Once you're done, create a PR here and a core developer will look at your code and review it.  He or she may ask for corrections to be made.  If the patch is clean and is a good addition to the library, it will be merged.  If for any reason the patch can't make it to the official master branch, then you can still use it on your side and create your own minimized versions of the library.

Before coding, you may expose what you want to do here, in this Issue first, to collect comments.

That's pretty much it.  Please, let us know if you have any questions.

**Comment by openlayersUser** [comment]
Hi adube,

This setRotation I fixed by editing ol3g.debug.js file. Now every setStyle will work without removing and adding features from layer. But I have one doubt. After editing in debug.js how to compile that file ? Can you please help me how to compile ol.debug.js file ? any online tools ?

**Comment by adube** [comment]
The explanations are right above your comment.  See: https://github.com/mapgears/ol3-google-maps/issues/147#issuecomment-277682036

**Comment by adube** [comment]
Your changes must be done on the original files, i.e. those in the `src` directory.  Then, you can build using the `make dist` command.

**Comment by openlayersUser** [comment]
Hi adube,

 setRoataion will effect only when we remove and add feature again to source. This is not supported by OL3-Google-Maps previously. I want to know in upcoming new releases this is coming or you are working on it. Can I expect this one in future or its already completed ??

**Comment by adube** [comment]
We are not working on this feature and is not expected in the near future.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
