### ISSUE TITLE
Support ol.geom.Circle

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#148]
This task is about supporting `ol.geom.Circle` as geometry type within OL3-Google-Maps.  It is currently not supported: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#circle-geometry

See also: https://github.com/mapgears/ol3-google-maps/blob/v0.12.3/src/gm/gm.js#L29-L52

**Comment by ogunnars** [comment]
When using interactions a fix is needed to get ol3-google-maps work on draw end.
Change the feature geometry to a polygon to enable switch bwteen different base layers 

....
				        var geom = feature.getGeometry();
				        // Fix to get google maps working while it does not support ol.geom.Circle
				        var precisionCircle = ol.geom.Polygon.fromCircle(geom, 128, 0);
				        feature.setGeometry(precisionCircle);
...

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
