### ISSUE TITLE
ol3gm.js not found

### ISSUE THREAD

**Issue by smartpaco** [mapgears/ol3-google-maps#155]
Hello,
In the quick start, you mention:
load the OL3-Google-Maps script included in the tarball of the version you downloaded, which already includes OpenLayers so you don't need to load OpenLayers too.
<script type="text/javascript" src="ol3gm.js"></script>

This file is not available in the repositories?
Many thanks.

**Comment by adube** [comment]
No, it's not.  The repository contains the source files.  The minimized version of the library is only found in the .zip files, which can be found in the releases: https://github.com/mapgears/ol3-google-maps/releases

Best regards
