### ISSUE TITLE
WMS source with '?' in the url fail with OLGM

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#158]
When using a WMS url that contains a `?` character in it, for example 'host://myserver/mapserv?map=/mymap.map', it fails because the url OLGM builds doesn't check if there's such a character.  It always adds one itself.

**Comment by ckapop** [comment]
Any updates to this or workarounds?

**Comment by adube** [comment]
No updates, but this shouldn't be too hard to fix.  We could use the OpenLayers' `ol.uri.appendParams` method instead of manually adding each param manually.

If you would like to work on a fix for this, I'd be happy to do a review.

**Comment by ckapop** [comment]
If we were to add manually where would be the best place to do this?

**Comment by adube** [comment]
@ckapop I ended up creating a patch, as it was simple enough for me to do rather than trying to explain how I'd like this to be fixed.  Would you please try the fix in #212 and tell me if that fixes your issue?

Thanks.

**Comment by ckapop** [comment]
I actually spent some time and fixed it as well. I will compare what I did with your fix.

However, we are still having an issue even after this fix with using setImageLoadFunction. It seems this doesn't update the source url_. We need because use a proxy to get at the WMS data. I am thinking this is due to the cache and relates to "View and Layers heralds do not handle Map's "change:target" #200"

I am trying to find a work around for this because I suspect it is a larger issue. Any ideas?

**Comment by adube** [comment]
It would be nice if you could provide a simple online demo of what you're trying to do that causes the issue, using jsfiddle or something like that.  This would help demonstrate the problem you're having.

I think the fix proposed in the PR is good to fix the issue described here.  Would you please tell me if the original issue you're having is fixed with the PR?

For any other bug/problem, please open an other issue or comment in an existing issue that describe the problem you're having.

Thanks for your time testing this.

**Comment by ckapop** [comment]
Yes, Your fix is essentially what I did. Not sure why you borrowed the ol.uri.appendParams function to create an olgm.uri.appendParams function. We have access to the ol.uri.appendParams, correct?

I will open another issue for the other problem. Thanks!

**Comment by adube** [comment]
@ckapop You are correct that normally we should have access to this method, but the way olgm is currently runs the example doesn't allow the use of anything that's not marked as `@api` in OpenLayers.  This is something that should be fixed once we change the way we package olgm.
