### ISSUE TITLE
Overview Map

### ISSUE THREAD

**Issue by rezvanshiravi** [mapgears/ol3-google-maps#161]
Hi,
I want to add overview map to my google layer. but when I add this control, overview map doesn't show properly. 
I do all of the overviewmap.js  but still not work.
My code attached below. Can read it and if there is error inform me, please?

  var Google_view=new ol.View({
			center: Google_center,
			zoom:12,
			minZoom:12,
			maxZoom:21,
			extent:Google_bounds,
			projection: 'EPSG:3857'
		});
	 
	  var googleLayer = new olgm.layer.Google({mapTypeId:google.maps.MapTypeId.HYBRID,visible:false});
	   
	 map.addLayer(googleLayer); 
googleLayer.setVisible(true);
			
map.addControl(panpanel); 

ov = new ol.control.OverviewMap({layers:[googleLayer]});
map.addControl(ov);
overviewMap = ov.getOverviewMap();
	var overviewOLGM = new olgm.OLGoogleMaps({
	 map: overviewMap,mapIconOptions: {
		useCanvas: true
         }
	})
			olGM.activate();
			overviewOLGM.activate();

**Comment by adube** [comment]
May be related to #117.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
