### ISSUE TITLE
conflict with ContextMenu of ol3-contextmenu.js

### ISSUE THREAD

**Issue by josephzhao** [mapgears/ol3-google-maps#168]
Hello All
I am using ol3-contextmenu.js ol3gm.js conflict with it.

Thanks

Joseph

**Comment by adube** [comment]
Hello,

Thanks for your interest in ol3gm.  Would you please provide more details about the issue?  Also, would you please provide a patch to fix this issue?  A contribution would be welcome.

Thanks.

**Comment by josephzhao** [comment]
Thank you for your email.
do you have ol3gm-debug.js, then I can use it to make debug and find the solution.

Thanks

**Comment by adube** [comment]
Hello,

Check the [Developing](https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md) instructions.  You'll need to download the source files using git.  Any changes made are made to the original source files, not `ol3gm-debug.js`.

Execute `make lint` and `make dist` to make sure that your patch is correct.  You can do: `make serve` and visit the examples to see them in actions.  You can create a temporary example that features the issue you're having and use that example as a sandbox to work on it.

HTH

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
