### ISSUE TITLE
Google maps as a layer in Geoext3 Tree Panel

### ISSUE THREAD

**Issue by kukumix** [mapgears/ol3-google-maps#169]
I'm trying to load Google Maps as a Layer in Geoext3 tree Panel. I'm using Ol3-Google-Maps. My code is:

    var googleLayer = new olgm.layer.Google({
        name: 'Google',
        title: 'Google',
        type: 'base',
        combine: 'true'
    });    

    olMap = new ol.Map({
        layers: [googleLayer, layerorto2016gv, layerlim],
        controls: controls,
        view: new ol.View({
            center: center,
            zoom: 15
        })
    });

    var olGM = new olgm.OLGoogleMaps({map: olMap}); // map is the ol.Map instance
    olGM.activate();               

    mapComponent = Ext.create('GeoExt.component.Map', {
        map: olMap
    });

I can't do it works. Can anybody help me? Sorry for my english

**Comment by adube** [comment]
Hello  Please, avoid cross-posting: https://gis.stackexchange.com/questions/237218/google-maps-as-a-layer-inside-geoext3-tree-panel

Please, try to load ol3gm-debug.js instead of ol3gm.js, which should help you finding the cause of the problem.

Any contribution or fix would be welcome.

**Comment by kukumix** [comment]
I've done and the error shown is:

Uncaught Error: Namespace "ol" already declared at Object.goog.provide.

Now I'm looking for a solution.
Thanks

2017-04-20 21:14 GMT+02:00 Alexandre Dubé <notifications@github.com>:

**Comment by adube** [comment]
Looks like you're loading OpenLayers twice.  Try to see where and load it only once.

**Comment by kukumix** [comment]
I've solved this deleting one of them. I've twice.
Now I haven't any error but google mapas layer doesn't appear.
When I tried the simple example I had problems with the css of the map. I
think I've the same problem. I've to think how to solve it.

2017-04-20 21:43 GMT+02:00 Alexandre Dubé <notifications@github.com>:

**Comment by kukumix** [comment]
It doesn't work. Now appears the following error:
		ol3gm-debug.js:91417 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
The problem is that the google layer doesn't appear inside de mappanel.

**Comment by adube** [comment]
Have you checked if this may be related to the issue mentioned here: https://github.com/mapgears/ol3-google-maps/issues/37#issuecomment-172858622

I suspect it may be the case.

**Comment by kukumix** [comment]
Yes, I've tried.

2017-04-21 14:04 GMT+02:00 Alexandre Dubé <notifications@github.com>:

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
