### ISSUE TITLE
olgm package for ES module bundlers

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [mapgears/ol3-google-maps#172]
We are currently moving our ol3-google-maps application to Webpack. Webpack and similar module bundlers work best using ES modules. Closure compiled bundles can be compatible with Webpack, but they lose significant advantages such as [tree shaking](https://webpack.js.org/guides/tree-shaking/). OpenLayers and ol3-google-maps can also easily be extended with ES modules.

In order to provide a specialized Interaction we are using our own fork of OpenLayers. Consequently we need a fork of ol3-google-maps as well in order to build against our own version of OpenLayers. As you can probably imagine we would like to extend OpenLayers functionality and avoid the hassle of maintaining forks. We are aware that it is possible (to an extent) to extend OpenLayers and ol3-google-maps without forks, but it gets hacky quite fast when you have to target minified builds. ES modules could be the solution to this.

@tschaub has shown that it is possible to generate ES modules from javascript targeting the closure compiler using jscodeshift, which is exactly how the [`ol` NPM package](https://www.npmjs.com/package/ol) which was introduced in 4.0.0 is provided. [See the PR that introduced this in OpenLayers](https://github.com/openlayers/openlayers/pull/6302). I highly suggest taking a look at the implementation.

I propose the creation of an `olgm` NPM package that will serve the same purpose as the `ol` NPM package. This would provide better support for module bundlers. `olgm` could depend on `ol` as a peer dependency to allow independent updates of OpenLayers.

I have experimented using the same approach. Generating the ES modules seems feasible. If you feel like you can publish and maintain this package I will gladly work with you to PR this in.

**Comment by adube** [comment]
@JamiesWhiteShirt Thanks for your interest in olgm.  There's already an NPM package, see: https://www.npmjs.com/package/ol3-google-maps.

If there are changes that would be required to be able for it to be used as ES module, I'd be happy to review a PR.

Please, note that I may be out for a few weeks and may not reply during that short period of time.

**Comment by JamiesWhiteShirt** [comment]
Yes, you have an `ol3-google-maps` package just as OpenLayers has the `openlayers` package. For convenience, OpenLayers uses the specialized package `ol` for ES modules, which is why I figured there could be a similar separate `olgm` package. Understandably there is a bit of maintenance involved with a separate package, but I don't know how else we should handle the peer dependency on `ol`.

It currently seems only a minor change is necessary in the code while the rest can be handled by jscodeshift. The package would also have to be set up and maintained.

**Comment by JamiesWhiteShirt** [comment]
Good news! I was successful in the creation of ES modules for ol3-google-maps. I was wrong in the assumption that only minor changes would be necessary in the code. OpenLayers has been doing a lot of work to facilitate ES module consumption. To make ol3-google-maps similarly compatible, I had to make similar changes. They are listed below.

**Removing dependency on the Closure Library**. OpenLayers has worked hard to remove this dependency. They completed this [almost a year ago](https://github.com/openlayers/openlayers/issues/4128). OpenLayers provides its own utilities that ol3-google-maps can depend on.

This means replacing assertions among other things:

```diff
-goog.asserts.assertInstanceOf(geometry, ol.geom.Geometry);
+ol.asserts.assert(geometry instanceof ol.geom.Geometry);
```

**Adding explicit requires of all used modules and submodules.** This is done inconsistently through ol3-google-maps, so a cleanup here is in order. This is required to make the generated import statements work.

This means for instance if `ol.geom.Geometry` is referenced, doing `require('ol')` is not enough; `require('ol.geom.Geometry')` is necessary.

**Renaming and moving files to match the provided module name**. This is also required to make the generated import statements work.

See files in the `herald` folder. For instance, the file `featureherald.js` provides the `olgm.herald.feature` module. It has to be renamed to `feature.js`.

`interaction/interactiondefaults.js` has to be moved to `interaction.js` because it provides the `olgm.interaction` module.

----

I have this working in a local copy. I will open a PR in the near future.

**Comment by JamiesWhiteShirt** [comment]
https://www.npmjs.com/package/olgm
