### ISSUE TITLE
View herald does not handle Map's "change:view"

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [mapgears/ol3-google-maps#176]
OpenLayers allows you to set the View on the Map instead of mutating the existing View. We found this to be a necessary approach when having to change the constraints on the Map's View.

I discovered that this approach tends to break the view herald. It would no longer sync with the position/resolution/rotation because it would be listening to a view that is no longer used by the map.

We found a way to work around it, but it should of course be fixed. I believe this can be solved with a cleverly placed `map.on('change:view')` somewhere. I will gladly help you fix this after the ES module PRs are handled.

**Comment by adube** [comment]
Yes, that would be great.

About the ES module PRs, I should be able to review them this week.  Thanks.
