### ISSUE TITLE
Problem switching to OSM map source

### ISSUE THREAD

**Issue by glchua2** [mapgears/ol3-google-maps#178]
Using example found in [http://mapgears.github.io/ol3-google-maps/examples/dist/examples/concept.html](here), when I click on Toggle OSM Layer, error message can be seen within console as shown in the screenshot below.

![ol3gm_error](https://user-images.githubusercontent.com/2323076/29358510-e068cf28-82ad-11e7-86b5-5c031eef49fc.png)

**Comment by adube** [comment]
Hi.  It seems to be working on my end.  What browser are you using?

**Comment by glchua2** [comment]
Now it works fine for me too, could just be some sporadic issue. Thanks for your time
