### ISSUE TITLE
Birds eye

### ISSUE THREAD

**Issue by iredmedia** [mapgears/ol3-google-maps#181]
Good afternoon! 

Is there any way to use the satellite imagery without allowing "birds eye"? I was using Leaflet Google Mutant before which didn't have this issue, and it seems like the imagery from this is different (not as high quality). 

Cheers!

**Comment by bampakoa** [comment]
@iredmedia you can set the `tilt` of the map to **0** using the `getGoogleMapsMap` method:

```
const olGM = new olgm.OLGoogleMaps({map: map});
olGM.getGoogleMapsMap().setTilt(0);
olGM.activate();
```

**Comment by iredmedia** [comment]
Thank you so much! (Smack my head)
