### ISSUE TITLE
Upgrade to latest OpenLayers

### ISSUE THREAD

**Issue by bampakoa** [mapgears/ol3-google-maps#184]
Hi all,

I would like to help towards upgrade of the library to the latest OpenLayers version and I have some questions to ask:

- I am currently using Windows as my preferred development OS and I noticed [DEVELOPING_WINDOWS](https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING-WINDOWS.md) guide . It requires installation of some tools that I would like to avoid. Is this the only way to develop? Are there any other alternative ways?
- I could not find any OpenLayers related tests. How do you test it in conjunction with the latest OpenLayers version, that it does not break?

**Comment by adube** [comment]
Hello.

About Windows: I've never tried it myself.  If you find a better alternate way to develop on Windows, please feel free to provide a patch for the instructions.

About tests: after upgrading, you need to:

 * read each OpenLayers "release note" between versions. There is code that changes from version to version, so adjustments are required.
 * run the `make dist` command.  It usually helps a lot for the above.
 * check the examples (the "concept" one has a lot of features) to test if everything works smoothly.

**Comment by adube** [comment]
Suggestion: it's a bit late for that, but I would have like to see 1 version of OLGM for each OL version. Do you think it would still be useful? Thoughts?

**Comment by bampakoa** [comment]
@adube IMO, the best option would be to have 1 OLGM for each OL-GM version 😏

**Comment by adube** [comment]
With GM, we don't have much options.  When Google decides to deprecated a version, it's no longer supported and one that tries to load it would have a newer version instead.

On the other hand, the code doesn't change much, i.e. it rarely does.  Only switching from a version to a newer one in the examples was enough to convice me that OLGM still worked with newest versions of GM.

So my opinion is this: I think we should only focus on synchronizing with OL, i.e. 1 OLGM version per OL, but as soon as Google Maps releases a new version of the JS API, then switch to it.

What do you think?

**Comment by bampakoa** [comment]
@adube What do you think about introducing a different build mechanism, like Gulp or Webpack, so that it can be more OS aware? It would be more easy for anyone to jump into and start contributing. We could add at least those targets from makefile that are needed for contribution only (not **dist** related targets).

**Comment by adube** [comment]
@bampakoa In my opinion, we should stick close to how OpenLayers does it.  OL-Cesium is an other good example of a library that combines OL to an external lib (in this case, it's Cesium) and they use the same type of "development" environment.  OLGM is like this too.  I wonder how people contribute to OL or OL-Cesium from a Windows OS...

I honestly don't know about these 2 libs, nor understand very much what they would add.

**Comment by bampakoa** [comment]
@adube I can see that OLGM uses Cygwin. Is there any possibility that we can neglect it when developing in Windows?

**Comment by adube** [comment]
>I can see that OLGM uses Cygwin

That's not entirely true.  It's what was documented to use for contributers that use Windows.  OLGM doesn't natively use Cygwin.

I never tried it (I'm not using Windows).  If you find a way not to use it, feel free to document it as an alternative.

**Comment by bampakoa** [comment]
@adube is this version of Java supported:

```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by adube** [comment]
@bampakoa yes.

**Comment by bampakoa** [comment]
@adube When I run `make dist-apidoc`, I get the following errors:

```
ERROR: Unable to parse a tag's type expression for source file /mnt/d/Dev/ol3-google-maps/externs/google_maps_api_v3_27.js with tag title "type" and text "{(function(google.maps.Data.Geometry): google.maps.Data.Feature)|undefined}": Invalid type expression "(function(google.maps.Data.Geometry): google.maps.Data.Feature)|undefined": Expected "!", "=", "?" or end of input but "|" found.
ERROR: Unable to parse a tag's type expression for source file /mnt/d/Dev/ol3-google-maps/externs/google_maps_api_v3_27.js with tag title "type" and text "{(function(google.maps.Data.Geometry): google.maps.Data.Feature)|undefined}": Invalid type expression "(function(google.maps.Data.Geometry): google.maps.Data.Feature)|undefined": Expected "!", "=", "?" or end of input but "|" found.
ERROR: Unable to parse a tag's type expression for source file /mnt/d/Dev/ol3-google-maps/externs/google_maps_api_v3_27.js with tag title "param" and text "{?=} opt_value": Invalid type expression "?=": Expected "!", "?" or "|" but end of input found.
ERROR: Unable to parse a tag's type expression for source file /mnt/d/Dev/ol3-google-maps/externs/google_maps_api_v3_27.js with tag title "param" and text "{?=} opt_value": Invalid type expression "?=": Expected "!", "?" or "|" but end of input found.
/mnt/d/Dev/ol3-google-maps/build/jsdoc/api/plugins/typedefs.js:12
    var types = param.type.names;
                           ^

TypeError: Cannot read property 'names' of undefined
    at addSubparams (/mnt/d/Dev/ol3-google-maps/build/jsdoc/api/plugins/typedefs.js:12:28)
    at exports.Parser.parseComplete (/mnt/d/Dev/ol3-google-maps/build/jsdoc/api/plugins/typedefs.js:58:9)
    at emitOne (events.js:121:20)
    at exports.Parser.emit (events.js:211:7)
    at exports.Parser.Parser.parse (/mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/lib/jsdoc/src/parser.js:183:10)
    at Object.module.exports.cli.parseFiles (/mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/cli.js:356:42)
    at module.exports.cli.main (/mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/cli.js:226:14)
    at Object.module.exports.cli.runCommand (/mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/cli.js:180:5)
    at /mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/mnt/d/Dev/ol3-google-maps/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
Makefile:63: recipe for target 'dist-apidoc' failed
make: *** [dist-apidoc] Error 1

```

**Comment by adube** [comment]
Mmm, I'm not sure where this comes from...  Maybe it's because the source from the v3_27 extern file contains code that can't be parsed by the current version of the compiler being used.

Try to upgrade to the latest version of closure-util, which would be 1.25.0 (if I remember correctly, it's closure-util's compiler that's used, but I'm not sure)...

Try this and report back.

**Comment by bampakoa** [comment]
@adube I updated closure-util to 1.25.0 and the error persists.

**Comment by adube** [comment]
Here's what I suggest: don't update the extern (for now).  OLGM doesn't use anything that's new in GM 3.27 anyway, so upgrading the extern is not mandatory at the moment.  Testing that the examples still work is more important.

What do you think?

**Comment by bampakoa** [comment]
Sure! I am currently writing a guide for developing in Windows 10 using the Ubuntu bash:

1. Should I append the content in DEVELOPING_WINDOWS or create a new one?
2. Should I add a note about the `dist-apidoc` problem?

**Comment by adube** [comment]
>Should I append the content in DEVELOPING_WINDOWS or create a new one?

Use the existing DEVELOPING_WINDOWS file.


>Should I add a note about the dist-apidoc problem?

You can create an issue with the description of what happens in there.

Thanks a lot for your work :)
