### ISSUE TITLE
How to package OpenLayers and Google Maps separately

### ISSUE THREAD

**Issue by tomn98** [mapgears/ol3-google-maps#198]
This is more of a question instead of an issue.   I didn't know where else I could simply post a question.   Currently, I have ol3-google-maps integrated into a visualization application.  I have a use case where I need to load just non-Google Maps.  In this case, I simply want to load the OpenLayers library without the google maps library integrated because I don't want to provide the Google Maps API key all the time.  Is there anyway I can separate ol3-google-maps into two separate libraries (for example, maybe ol3.js and google-maps.js) so I can first load ol3.js by default, then dynamically load google-maps.js (and provide the Google Map API key at that point) if I see there's a Google Map configured?

Thanks.

**Comment by adube** [comment]
Hi @tomn98 

We faced tis kind of issue in the past.  We ended up picking this solution: we made OLGM "compatible" without loading Google Maps.  See an example of what we did:

https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/gm/imageoverlay.js#L45-L47

So, technically, you can load OLGM without GoogleMaps and it won't throw any error.  If you try to create anything that requires OLGM, then you would end up with errors.

In the end, the only thing you should be concerned with is whether to load Google Maps API or not.

Please, let us know if that helped / answered your question.  You can close this if it did.

**Comment by tomn98** [comment]
Thanks, @adube, for responding so quickly.   Your response helped, but I don't think it completely answered my question.

Let me try to clarify.  I'm using OLGM in two different scenarios in my visualization application:
   1.  Map containing Google and non-Google layers
   2.  Map containing only non-Google layers (user is not be expecting to include Google Map API 
        key for this scenario)

My issue has to do with scenario #2 above.  I am able to use OLGM with scenario #2 and there are no errors like you mentioned.  The problem is requiring a Google Map API key when there are no Google layers at all.  To use OLGM, isn't it a prerequisite to include the Google Map API key?  That's why in my earlier post  I was asking to see if there was a way to separate OLGM into two separate libraries so that I won't have to include the Google Map API key for scenario #2.

**Comment by adube** [comment]
@tomn98 You don't need a Google Map API key to "include" OLGM.  The key is only required when loading Google Maps API.

Does that help?

**Comment by tomn98** [comment]
@adube I did a few tests using the latest version 0.17.0 of ol3gm.js based on your post.  It's working properly when there are no Google layers.  But, when there is a Google layer, an error occurs.  Here are my steps:
  
1. I included ol3gm.js statically
2. Load a map w/o Google layer.  Works properly.
3. I then load the Google Maps API using my key,
4. Try to load a map with Google layer.  I get the following error when creating the map with the line
    var olGM = new olgm.OLGoogleMaps({map: map});

    Uncaught TypeError: this.setMap is not a function
       at new Lf (ol3gm.js:123)
       at new Bh (ol3gm.js:174)
       at new Si (ol3gm.js:203)
       at new Bk (ol3gm.js:229)
       at indx.ui.gismap.GISMapItem.buildGISMap (gisMapItem.js:411)
5. If I dynamically reload ol3gm.js, then load the map again, the error goes away and everything works.

This leads to think that there's still some code in OLGM (such as this.setMap in the error above) that relies on the Google Maps API being loaded "before" they get included.  Could that be possible?

**Comment by adube** [comment]
>This leads to think that there's still some code in OLGM (such as this.setMap in the error above) that relies on the Google Maps API being loaded "before" they get included. Could that be possible?

That is correct.  You must have Google Maps loaded before loading OLGM if you intent to use OLGM.

**Comment by tomn98** [comment]
@adube That's what I thought.  This leads back to my original question.  Is it possible during building/packaging of OLGM to not have OpenLayers included into OLGM and simply left as a separate library?  The end-result could be something like ol3.js and and google-maps.js, where google-maps.js requires ol3.js to be loaded first.

**Comment by adube** [comment]
I don't think that's currently possible, no...

**Comment by bampakoa** [comment]
@tomn98 I had the same problem and ended up on maintaining separate **index.html** files, one with Google Maps API and OLGM and another with OLGM only.

**Comment by godbit** [comment]
I had the same issue because my application had to parse config to determine which api key to use. This forced me to dynamically include Google maps. See:

```ts
 /**
   * Dynamically loads the Google maps api using apikey from config.
   * @param callback function to run once the script has finished loading.
   */
  private loadGoogleMapsApi(callback: () => void) {
    const apiKey = config.googleMaps.apiKey;
    const scriptElement = document.createElement('script');
    scriptElement.type = 'text/javascript';
    scriptElement.src = `https://maps.googleapis.com/maps/api/js?key=${apiKey}`;
    scriptElement.onload = callback;
    document.head.appendChild(scriptElement);
  }
```
This caused the ```Uncaught TypeError: this.setMap is not a function``` error when using a regular webpack import of OLGoogleMaps since it is initialized before Google maps has loaded.

I resolved this by using a dynamic import of OLGoogleMaps in the callback of ```loadGoogleMapsApi```. Then waiting for it to resolve before initializing the map.

```ts

function normalizeCommonJSImport<T>(importPromise: Promise<T>): Promise<T> {
    // CommonJS's `module.exports` is wrapped as `default` in ESModule.
    return importPromise.then((m: any) => (m.default || m) as T);
}

...

private initializeMapWithGoogle() {
    const OLGoogleMaps = await normalizeCommonJSImport(import(/* webpackChunkName: "olgm" */ 'olgm/OLGoogleMaps.js'));
    const map = new OlMap({....});
    const olGM = new OLGoogleMaps({ map });
   ...
}
```
Im using Angluar and I used this for reference: https://medium.com/lacolaco-blog/angular-dynamic-importing-large-libraries-8ec079603d0


These steps resolved the issue for me so I'm leaving it here as a reference if someone else has the same problem.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
