### ISSUE TITLE
Error setting EPSG: 3857 in View Layer

### ISSUE THREAD

**Issue by esleytecnologia** [mapgears/ol3-google-maps#199]
When I set up **EPSG: 3857** in the **View Layer**, Google's base map does not work.

Here is my code below:

`var projection = new ol.proj.Projection({
        code: 'EPSG:3857',
        units: 'm'
    });
`

`var view = new ol.View({
        center: ol.proj.fromLonLat(center),
        projection: projection,
        zoom: 12,
        maxZoom: 20,
        minZoom: 12
    });`

**Comment by adube** [comment]
Hi.  I don't know why, but it works if you use this `var projection = ol.proj.get('EPSG:3857');` to get the projection instead.

Would you please try it?

**Comment by esleytecnologia** [comment]
Using `var projection = ol.proj.get ('EPSG: 3857');` the base map of Google has reappeared, but the Layer that I look for in GeoServer does not load.

**Comment by bampakoa** [comment]
@esleytecnologia Can you setup a plnkr for this?

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
