### ISSUE TITLE
View and Layers heralds do not handle Map's "change:target"

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [mapgears/ol3-google-maps#200]
It is possible to change the target element of a Map. It is also possible to construct a Map without a target element and set it later.

The Layers herald assumes the Map has a target element on construction, and that the target element will not change. https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/herald/layers.js#L111-L121

This isn't a big issue (we were able to work around it) but worth reporting.

**Comment by adube** [comment]
Indeed, it would be nice to enhance this.  Thanks for the report.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
