### ISSUE TITLE
Travis fails the tests due to SSL handshake failure, works locally

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#201]
Travis is reporting an error on `make test` that runs just fine on Node 8 and 9 locally.

The issue is that PhantomJS is silently unable to load the Google Maps API script on Travis. This is not reported by mocha-phantomjs-core because it is configured to ignore resource errors, seemingly because of some failing telemetry by the Google Maps API.

[As you can see in this experiment](https://travis-ci.org/mapgears/ol3-google-maps/jobs/326714466#L1359), Travis fails to load the Google Maps API script because of "SSL handshake failed".

Until a fix is found, the tests are going to be removed from Travis checks.

**Comment by JamiesWhiteShirt** [comment]
This appears to be fixed with the ES modules refactoring.

**Comment by adube** [comment]
Indeed.  Closing now...
