### ISSUE TITLE
Extjs problem.

### ISSUE THREAD

**Issue by lewinmadrid** [mapgears/ol3-google-maps#204]
When combining extjs and ol3-google-maps, on window resize, the map is not updated correctly, leaving the map not centered and/or blank areas. After a second window resize the map is drawn correctly.
The same thing happens with or without Geoext.
I'm currently using extjs 6.2.
###
	region:'center',
	layout:'fit',
	title:'Map',
	bodyPadding : 0,
	listeners:{
		afterrender:function(){
			
			var googleLayer = new olgm.layer.Google();
			var coords = ol.proj.transform([-2, 40.18], 'EPSG:4326', 'EPSG:3857');

			var view = new ol.View({
			  center: coords,
			  zoom: 6
			});

			this.map = new ol.Map({
				interactions: olgm.interaction.defaults(),
				target: this.body.dom.id,
				layers: [googleLayer],
				view: view
			});  
			
			var olGM = new olgm.OLGoogleMaps({map: this.map}); 
			olGM.activate();
		}
	}

**Comment by adube** [comment]
OLGM manipulates the target of the map a lot, especially upon activation (if we end up with a base layer that's a google layer).

Try activating olGM asynchronously, i.e. wrap it around a `window.setTimeout` to see if it could fix the issue.

**Comment by lewinmadrid** [comment]
No luck with the timeout.
### 	
	setTimeout(function(){
		var olGM = new olgm.OLGoogleMaps({map: olmap});
		olGM.activate();
	}, 1000);

**Comment by bampakoa** [comment]
@lewinmadrid can you setup a plnkr for that?

**Comment by lewinmadrid** [comment]
Had problems getting a plunkr to work. Sorry.
I've attached a zip file that includes the dependencies.

[ol4_ext6.zip](https://github.com/mapgears/ol3-google-maps/files/1706954/ol4_ext6.zip)

**Comment by bampakoa** [comment]
@lewinmadrid You need to notify the browser window for the resizing

```
resize: function () {
    window.dispatchEvent(new Event('resize'));
}
```

**Comment by lewinmadrid** [comment]
Thanks, that fixed it!
