### ISSUE TITLE
error compile v0.19.0

### ISSUE THREAD

**Issue by geopamplona** [mapgears/ol3-google-maps#208]
Hello, 

I m trying compile new release, but i have next error:

$  node build/build.js build/ol3gm.json ol3gm-custom.js
info ol3-google-maps Parsing dependencies
info ol3-google-maps Compiling 384 sources
ERR! compile dist/exports.js:2826: ERROR - Property extent_ never defined on ol.interaction.Extent.Event.prototype
ERR! compile     ol.interaction.Extent.Event.prototype.extent_);
ERR! compile                                           ^^^^^^^
ERR! compile
ERR! compile
ERR! compile 1 error(s), 0 warning(s), 97.5% typed
ERR! compile
ERR! Process exited with non-zero status, see log for more detail: 1

Before I compile, install npm dependencies, and regenerate exports node build/generate-exports dist/exports.js

There are some well tutorial to compile this, without fails? 
we want to update this frequenctly..

thanks :)

**Comment by adube** [comment]
Hello there!

The instructions to build the library are included in the [DEVELOPING.md](https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md#working-with-the-build-tool) file, i.e. it's with the build tool.

Here's what I did:

```
git clone https://github.com/mapgears/ol3-google-maps.git
cd ol3-google-maps
nvm use 8
npm install
make dist
```

and it compiled successfully.  I also tried using npm:

```
npm install ol3-google-maps
cd node_modules/ol3-google-maps
nvm use 8
npm install
make dist
```

You don't need to generate the exports anymore.  It used to be useful back when the library was not compiled with OpenLayers.  It is, now.

Please, let us know if that helps.

**Comment by geopamplona** [comment]
perfect !

clean compile without errors.

thanks very much
