### ISSUE TITLE
draw interaction condition parameters

### ISSUE THREAD

**Issue by flyfishMT** [mapgears/ol3-google-maps#210]
Why am I getting a different object as the parameter to the condition method in ol3-google-maps v0.19 than I do with stock openlayers 4.6.4?

The following code works in openlayers 4.6.4, but `pointerEvent `does not exist on parameter `e` with ol3-google-maps.

```
let drawCondition = function(e) {
	// only draw on left click
	return (e.pointerEvent.buttons === 1);
}
draw = new ol.interaction.Draw({ source: source, type: drawType, condition: drawCondition });
map.addInteraction(draw);
```

**Comment by adube** [comment]
Hello @flyfishMT.  Thanks for your interest in ol3-google-maps!

Okay, I understand what's going on.  Let me explain.

`e` is an instance of the `ol.MapBrowserPointerEvent` class.  See: https://github.com/openlayers/openlayers/blob/v4.6.4/src/ol/mapbrowserpointerevent.js#L16

As you can see, this class does have the `pointerEvent` property you are referring.  However, it is not an "API" property, i.e. when we use a minimized version of OpenLayers, it is not exposed.  It is present, but renamed as something else (for example `abc`).  The name becomes available for internal use only.

I don't know how you're currently using OL, i.e. if you either use it as an uncompressed version (debug) or as a module where the files are manually included and you would have access to such properties, but in ol3-google-maps OL is included as its minimized version, therefore thiis property is not available.

However, after testing, I found that you could access your `buttons` in an other way.  

`ol.MapBrowserPointerEvent` inherits `ol.MapBrowserEvent`, see: https://openlayers.org/en/latest/apidoc/ol.MapBrowserEvent.html#originalEvent

The `originalEvent` property is marked as `@api`, therefore it is exposed and available in the minimized version of the build.

So, you can do this instead: `e.originalEvent.buttons`.  It should work.  Let us know how it went for you.

**Comment by flyfishMT** [comment]
@adube - I would rather use the actual API I didn't realize I wasn't.  Your solution works great. Reading through openlayers issues, I found this which is related - [5453](https://github.com/openlayers/openlayers/pull/5453) 
And I should have said originally,  thanks for your hard work on this library!

**Comment by adube** [comment]
Thanks for the feedback and kind words.  Happy coding!
