### ISSUE TITLE
When using setImageLoadFunction it doesn't update parent source layer url.

### ISSUE THREAD

**Issue by ckapop** [mapgears/ol3-google-maps#213]
The [setImageLoadFunction](https://openlayers.org/en/latest/apidoc/ol.source.ImageWMS.html#setImageLoadFunction) in OpenLayers is useful to proxy to another url for WMS loading. With OL we could use this function and the source layer that contained the image would update its url as well at the image.

With ol3gm it seems after this image callback is called the source layer url doesn't change along with it which then wont load the correct WMS image because the image url was changed.

**Comment by adube** [comment]
I don't have much knowledge of this feature.  It would be nice if you could produce a small online example that would demonstrate what lacks in olgm to support this.  Or even better you could also create a branch and add an example in there that demonstrates the issue.  This branch could be the sandbox where we could debug/work on this issue.

If you're willing to work on this, I'd be happy to review.  Please, let me know if you do.

Thanks and happy coding.

**Comment by ckapop** [comment]
I will try and create a example soon. Basically it has to do with the setImageLoadFunction callback which allows you to change the image's src url to something different (proxy url).

The problem is that if you supply a callback it gets triggered before this function: olgm.herald.ImageWMSSource.prototype.updateImageOverlay_  which generates a new url using generateImageWMSFunction_. This url never goes through the setImageLoadFunction callback that the image uses. 

Therefore the url is incorrect. This is only an issue when you need to change the url of an image via  setImageLoadFunction (using a proxy url).

**Comment by adube** [comment]
Mmm... this makes it difficult (maybe even not possible) for olgm to be aware of this url...  It's defined within a method that's not accessible to olgm... mmm...

I don't have any smart solution for this (yet)...  Maybe we could define a custom parameter (something like `source.set("myCustomUrl")` and make olgm look for this `myCustomUrl` from there instead? I suspect you don't want to change the source url directly (there has to be a reason not to).

If you have any idea, don't hesitate to share it.

**Comment by ckapop** [comment]
I did find a workaround that seems to work. Inside the `setImageLoadFunction ` function that updates the img url I also updated the url of the source like this:
```
source.setImageLoadFunction((img, src) => {
  img.getImage().src = this.getNewUrl(src)
  if (typeof this.getSource === 'function') {
    // this is a layer object
    this.source_.url_ = this.getNewUrl(olgm.herald.ImageWMSSource.prototype.generateImageWMSFunction_(this)) 
  }
})
```

It seems to work in our initial tests.

**Comment by adube** [comment]
Thanks for sharing this.  I know that `this.source_.url_ = ...` would not work compile because `url_` is a private property.  It's fine to override them when you know what you're doing, but just beware that these properties are supposed to be private for a reason.

This kinda looks like what I had suggested, but instead of setting the `url_` private property, we could do a `source.set("olgmAlternateUrl", url)` and look for the property in the olgm herald, i.e. `source.get("olgmAlternateUrl"l)`.  I still think that this approach would not be very smart, but the compiler wouldn't complain about it.

**Comment by ckapop** [comment]
Yes, I know it is not ideal and I agree. I tried initially to use this.source_.setUrl(newUrl) but it wouldn't work. Its seemed to trigger the `setImageLoadFunction ` again and then just loop. 

I do like your idea better. I will try switching to that after we confirm we are on the right track after testing.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
