### ISSUE TITLE
Update to OpenLayers 5

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [mapgears/ol3-google-maps#226]
[OpenLayers 5 was recently released.](https://github.com/openlayers/openlayers/releases/tag/v5.0.0)

OpenLayers has now migrated all their code to ES modules, which breaks the development and build process of ol-google-maps. As previously stated, ol-google-maps should also migrate to ES modules.

The code shifting introduced in #175 can be used to migrate the current source, but tests and examples will have to be updated as well.

**Comment by JamiesWhiteShirt** [comment]
@adube Just letting you know that I'm working on this in the [`olgm` branch of my fork](https://github.com/JamiesWhiteShirt/ol3-google-maps/tree/olgm).

There has been a lot of innovation in the OpenLayers development workflow that I am trying to inherit as well.

**Comment by adube** [comment]
The code of OLGM has been migrated to ES modules.  This is now fixed.
