### ISSUE TITLE
Single tile WMS layer no longer fluid with latest versions of Google Maps API

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#228]
Google Maps recently developed a new renderer for their map, as mentioned here: https://developers.google.com/maps/documentation/javascript/new-renderer

With this new renderer, the way OLGM handles the WMS single tiled layers is no longer fluid.  While animating, the image seems to slide.  Here's how it looks like now:

![output](https://user-images.githubusercontent.com/432436/44150956-24c04bee-a06f-11e8-9f20-ae3679310125.gif)

The way single images are handled will need to be changed in order to have the old "look and feel" back.

**Comment by justinstenning** [comment]
@adube any ideas on how to implement these changes? I am working in this area for the next few months so could look into it if I had some pointers.

**Comment by adube** [comment]
@spazzarama Not exactly, but I would start by looking at this example as a point of entry to a potential solution: https://developers.google.com/maps/documentation/javascript/examples/maptype-image

The `google.maps.ImageMapType` could be solution.
