### ISSUE TITLE
Incorrect NPM publication

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [mapgears/ol3-google-maps#230]
The NPM package currently doesn't work as intended. It appears the entire repository has been published to NPM, which is not the intended procedure.

The `build-package` task defined in package.json is designed to create a publishable package in `build/olgm`. This assigns a version constant and creates a simplified package.json, as defined in `tasks/prepare-package.sh`. I understand this might be somewhat unconventional. It is the publishing workflow used by OpenLayers.

I should have informed you about this, apologies.

**Comment by adube** [comment]
My apologies.  How it was done is the way I was used to.  I'll make an other release, no worries.

**Comment by adube** [comment]
Please, let me know if that's okay with you: https://www.npmjs.com/package/olgm

I also recommend that we copy the readme file.

**Comment by adube** [comment]
Fixed in #231
