### ISSUE TITLE
Instructions how to use the new OLGM package

### ISSUE THREAD

**Issue by bampakoa** [mapgears/ol3-google-maps#232]
You mentioned in [OLGM v1.0.0-beta.2](https://github.com/mapgears/ol3-google-maps/releases/tag/v1.0.0-beta.2) release instructions that there is no distributed package anymore and one should build its own OL-OLGM bundle. Is there any guide on how to do this?

**Comment by adube** [comment]
Building OLGM and OL alongside your own project should work.  You can try to follow this tutorial: http://openlayers.org/en/latest/doc/tutorials/bundle.html

Install `olgm` as well, i.e. `npm install olgm`.

You can also look at the examples in OLGM: https://github.com/mapgears/ol3-google-maps/blob/master/examples/simple.js

Please, let us know if that helped.

**Comment by bampakoa** [comment]
@adube Got it! I thought that we need to have separate bundles but in my case webpack did the trick. Everything worked perfect in our application with the new version. Good job to all!

**Comment by adube** [comment]
@bampakoa Thank you very much for the nice feedback!
