### ISSUE TITLE
ol3-google-maps in ionic application

### ISSUE THREAD

**Issue by meneva** [mapgears/ol3-google-maps#233]
Hello I am trying to implement ol3gm into my ionic application but it just shows "Uncaught (in promise): ReferenceError: olgm is not defined" my code is as below:
`import Map from 'ol/Map.js';
import GoogleLayer from 'olgm/layer/Google.js';
import {defaults} from 'olgm/interaction.js';
import OLGoogleMaps from 'olgm/OLGoogleMaps.js';

ngOnInit() {
        console.log(window.localStorage['userInfo']);
        var center = [-7908084, 6177492];
		// This dummy layer tells Google Maps to switch to its default map type
		const googleLayer = new GoogleLayer();
		var map = new Map({
		  // use OL3-Google-Maps recommended default interactions
		  interactions: defaults(),
		  layers: [
		    googleLayer
		  ],
		  target: 'map',
		  view: new olgm.View({
		    center: center,
		    zoom: 12
		  })
		});
		var olGM = new OLGoogleMaps({map: map}); // map is the ol.Map instance
		olGM.activate();
}
`
and my html file:
<script  type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?v=3&key=<my_google_key>">
</script>
<script type="text/javascript" src="ol3gm-debug.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.1/ol.css" type="text/css">
<link rel="stylesheet" href="http://dev5.mapgears.com/ol3-google-maps/css/ol3gm.css" type="text/css" />
  <div id="map" class="map"></div>

**Comment by bampakoa** [comment]
@meneva which version of the library do you use?

**Comment by meneva** [comment]
thanks bampakoa... I am using olgm Version: v0.20.0

**Comment by bampakoa** [comment]
Your source code tries to use [OLGM](https://www.npmjs.com/package/olgm) 1.0.0 which is currently in beta. I think that you need [OL3GM](https://www.npmjs.com/package/ol3-google-maps) package.

**Comment by meneva** [comment]
can u pls suggest me how i can import ol3gm into my ionic app. I just stuck on the matter.

**Comment by bampakoa** [comment]
Check the [quick start](https://github.com/mapgears/ol3-google-maps/tree/v0.20.0) details of the OL3GM package.

**Comment by meneva** [comment]
yes... I followed the example given in OL3GM package... but it always shows olgm undefined error. It's too much frustrating. No example for ionic apps

**Comment by bampakoa** [comment]
Where do you reference the bundle of OL3GM in your code?

**Comment by adube** [comment]
@meneva If you're using version v0.20.0, then you shouldn't use 'import'.  The live examples still use v0.20.0, i.e. https://github.com/mapgears/ol3-google-maps#live-examples, so you could look at the source code of those examples to see how to use ol3gm.

See an example:

 * http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.html
 * source code: http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.js

Let us know if that helped.

**Comment by meneva** [comment]
I think the ol3gm.js file is not included properly in my script. can u pls tell us how to include 
<script src="../ol3gm.js"></script>
into ionic view file. As far as i know it should be imported to module file(**xyz.ts** file) not in the view file.

**Comment by bampakoa** [comment]
@meneva I am not very comfortable with Ionic but I think that you cannot include a Javascript file inside an Ionic view using the `script` tag. Usually, this type of asset is added in the `index.html` file or in a configuration file if you are using a bundler such as webpack. Anyway, this type of question would be a better fit for SO or Ionic forums.

**Comment by YoussefTizi** [comment]
hi @meneva  are you find any solution about this issue?

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
