### ISSUE TITLE
Ordering of the overlays gets broken when google maps layer is used

### ISSUE THREAD

**Issue by minminminminminmax** [mapgears/ol3-google-maps#235]
We have olgm, osm as baselayers and several  TileWMS overlays 
To show/hide layers layer.setVisible(value) is used.

Ordering of overlays gets broken when google maps is enabled, so top most  becomes the overlay which is lastly made visible.

This behaviour happens only when googlemaps layer is in use are used and not in other case (with OSM and other Tile layers).
Switching between googlemaps layers (i.e. from gphy to gsat) restores the correct  layer ordering. But still after changing visibility of overlays the visible becomes the lastly made visible layer, what is breaks original layers order.

Could you please advice how to fix that?

**Comment by adube** [comment]
Would you please provide a live and short examples that demonstrates the issue?  I've looked at the existing examples and could not reproduce it using them.  Knowing what configuration are used to reproduce the issue would help figuring out where it comes from.

Thanks.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
