### ISSUE TITLE
Two finger pan is not smooth in touch screens

### ISSUE THREAD

**Issue by balab2020** [mapgears/ol3-google-maps#236]
I have tested greedy touch option with google map, it is not smooth. I mean, map does not pan when I use two finger drag/pan. It pan to map at the end of gesture complete. 

Also, I noticed that, google map instance is created with draggable with false in options. that property is deprecated now. Please refer google API.

https://developers.google.com/maps/documentation/javascript/interaction

**Comment by balab2020** [comment]
You can test this behavior on any touch screen using two fingers pan with http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.html 

It works smoothly on google maps page https://www.google.co.in/maps

**Comment by adube** [comment]
@balab2020 Thanks for reporting.

Would you please contribute a patch to fix this issue?  I would gladly review.  Thanks.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
