### ISSUE TITLE
Popup with nav-tabs do not work in openlayers 3

### ISSUE THREAD

**Issue by Nathanfrduarte** [mapgears/ol3-google-maps#243]
I have a map with openlayers3, made with ol3-gm, and a marker in it. This marker has a popup in which I used the openlayers examples, everything works fine. The problem is in the popup. It was done using nav-tabs from the bootstrap. It works perfectly when it's separate from the project, but when placed in the marker's popup, it does not work. The popup opens normally, but the tabs do not work. What is the popup problem? Is there any openlayers conflict with the bootstrap?

_I'm using bootstrap 3.3.7 and jQuery 3.3.1_

**I've already tried:**

1 - I've done click event functions with jQuery on the tabs to open them manually, but it did not work, the problem continued.

2 - I've also tried different ways to create the popup, like the bootstrap popup. Nothing has changed.

**Code of the map (it works well)**

```
// Mapa de Satelite
var googleLayer = new olgm.layer.Google({
    mapTypeId: google.maps.MapTypeId.SATELLITE
});
// criação do mapa
var map = new ol.Map({
    interactions: olgm.interaction.defaults(),
    layers: [
        googleLayer,            // Camada Goolgle maps
        vectorBetimBranco
    ],
    target: document.getElementById('map'),

    controls: ol.control.defaults({

        collapsible: false,
        zoom: false,
        attribution: false,
        rotate: false

    }),
    view: new ol.View({
        center: [-4919247.25998, -2266063.6466],
        zoom: 12,
        minZoom: 5,
        maxZoom: 19,
        projection: 'EPSG:3857'
    })
});
// Activate the library
var olGM = new olgm.OLGoogleMaps({ map: map });
olGM.activate();
```

**CSS**

```
.map {
    position: absolute;    
    height: 100%;
    width: 100%;
}

body {
    margin: auto;
}

.popover{
    max-width: 434px;
}
```

**Code of the marker (it works well)**

```
var vetorCoordenadas = new ol.source.Vector({});

mark1 = new ol.Feature({
    geometry: new ol.geom.Point([-4919247.25998, -2266063.6466]),
    type: "contrapartida"
});

// icone
m1style = new ol.style.Style({
    image: new ol.style.Icon({
        anchor: [0.4, 38],
        anchorXUnits: 'fraction',
        anchorYUnits: 'pixels',
        src: 'img/mark2.PNG'
    })
});

mark1.setStyle(m1style);
vetorCoordenadas.addFeature(mark1);

var vetorAlvaras = new ol.layer.Vector({
    name: 'vetorAlvaras',
    source: vetorCoordenadas
});

map.addLayer(vetorAlvaras);
```

**Code of the popup event**

```
var element = document.getElementById('popup');
var popup = new ol.Overlay({
    element: element,    
    stopEvent: true,
    autoPan:true,
    autoPanAnimation: {
        duration: 250
    }
});
map.addOverlay(popup);

// display popup on click
map.on('singleclick', function (evt) {
    $(element).popover('destroy');

var feature = map.forEachFeatureAtPixel(evt.pixel, function (feature, layer) {
    if (layer.get('name') === 'vetorAlvaras') {
        return feature;
    }
});

if (feature.get('type') === "contrapartida") {
    var coordinates = evt.coordinate;
    popup.setPosition(coordinates);

    $(element).popover({
        'html': true,
        'placement': "top",
        'animation':false,
        'content': $('#popoverContent').html()
    });

    $(element).popover('show');

    } else {
        $(element).popover('destroy');
    }
});
```

**Code of the Popup (Workinh in JSFiddle, but not in my project)**

[code on JSFiddle](https://jsfiddle.net/nathanfrduarte/5mL6esz2/)

**Comment by adube** [comment]
Your issue is well explained and I found myself having similar problems with bootstrap tabs when adding them in elements that are in an OL map.  Your solution 1) fixed the problem for me.

I'm guessing it is not a problem related to OLGM itself, but without actually being able to see it in action there isn't much that can be done.

Would you please create a small JSFiddle that would reproduce the problem?  That could help understanding what's happening.

**Comment by Nathanfrduarte** [comment]
> Your issue is well explained and I found myself having similar problems with bootstrap tabs when adding them in elements that are in an OL map. Your solution 1) fixed the problem for me.
> 
> I'm guessing it is not a problem related to OLGM itself, but without actually being able to see it in action there isn't much that can be done.
> 
> Would you please create a small JSFiddle that would reproduce the problem? That could help understanding what's happening.

Well, I solved the problem, not the way I'd like it, but ... okay. I had to make the popup tabs with pure html, with css and javascript obviously. I did not find out why the bootstrap did not work.
I'll post a JSFiddle with my solution later.
But thanks to you.

**Comment by adube** [comment]
Glad to hear you were able to solve it.  I'll close this issue now.

Happy coding!
