### ISSUE TITLE
Support for GeometryCollection in VectorFeatureHerald

### ISSUE THREAD

**Issue by justinstenning** [mapgears/ol3-google-maps#255]
Currently a geometry of GeometryCollection is not supported by the VectorFeatureHerald and results in the following assertion failure: `Assertion failed: Expected geometry to be module:ol/geom/Point|MultiPoint|LineString|MultiLineString|Polygon|MultiPolygon`

Google Maps API appears to support a GeometryCollection by passing the sub-geometries to the constructor of https://developers.google.com/maps/documentation/javascript/reference/data#Data.GeometryCollection

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
