### ISSUE TITLE
Google Zoom and point

### ISSUE THREAD

**Issue by yungfei1989** [mapgears/ol3-google-maps#26]
Dear,

I have implement your google code in my map. Why there is problems with zoom ar and point position display. Please help me to solve it.
1. when load first time with google map, there is a problem with zoom bar, but if load with another map at first time, there is not problem.
2. My marker position is different when I use google map and another map. Why it can be different. Poligon and line no problem, but point have problem.

my link : http://map.setiabudi.co.id/examples/test/map.html
source link : http://map.setiabudi.co.id/openlayers3-9.rar

Please help me to solve it..
wating for your reply..thx

**Comment by adube** [comment]
Hi,

  For the zoom bar problem, try to wrap the activation of olgm around a setTimeout (it's not pretty, but should work):

```
window.setTimeout(function() {olGM.activate();}, 0);
```

About the offset if the icon, try to set an anchor and size to the style.  See this example, which demonstrates a way to make it work properly:  http://dev5.mapgears.com/ol3-google-maps/examples/icon.html

Please, let me know if that helped.

**Comment by yungfei1989** [comment]
dear adube,

All solve the problem, but for zoom bar can you find another way to solve it without set time out? Because it is weird. We don't know how long the time we need to load google. Sometimes the zoom bar still error.

**Comment by adube** [comment]
For now, I don't have any more way to fix this.

**Comment by adube** [comment]
FYI, an [issue](https://github.com/openlayers/ol3/issues/4494) has been filed within the OL3 project itself which fits the description of the issue you're having (and that I also had).  I'll keep an eye on it as it may as well fix our issue, here.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
