### ISSUE TITLE
Release new NPM package

### ISSUE THREAD

**Issue by boomdrak** [mapgears/ol3-google-maps#260]
Hi there,
We need a new NPM package including some merged PRs in master branch.
Is it possible to release a new package?

https://www.npmjs.com/package/olgm

**Comment by adube** [comment]
Yes.  I'll take care of it this weekend.

**Comment by boomdrak** [comment]
Just dandy! :D

**Comment by adube** [comment]
The new 1.3.0 release is now available on npm.  Thanks to all the contributors and happy coding!

https://www.npmjs.com/package/olgm
