### ISSUE TITLE
Setting minZoom to larger than 0 breaks Google layer

### ISSUE THREAD

**Issue by justinstenning** [mapgears/ol3-google-maps#264]
Setting minZoom of the View to a value other than 0 causes Google layer to display the incorrect zoom and will remain at an incorrect zoom compared to the Open Street Map layer.

For example when setting the minZoom of the concept example to 1, the Google layer appears more zoomed in than the initial zoom of 4, toggling between Google and OSM you can see that OSM is still correct. Panning the map will also demonstrate the "wrongness" as it will scroll at a speed relative to the correct zoom of 4.

```
const map = new Map({
  // use OL3-Google-Maps recommended default interactions
  interactions: defaultInteractions().extend([
    new Drag()
  ]),
  layers: [
    osmLayer,
    new GoogleLayer()
  ],
  target: 'map',
  view: new View({
    center: transform([lng, lat], 'EPSG:4326', 'EPSG:3857'),
    zoom: zoom,
    minZoom: 1
  })
});
```

Incorrect (minZoom: 1):
![image](https://user-images.githubusercontent.com/933730/64098813-21b32100-cdab-11e9-98ec-960ac70d52ff.png)

Correct (minZoom: 0):
![image](https://user-images.githubusercontent.com/933730/64098782-119b4180-cdab-11e9-91b6-09f907ddb299.png)

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
