### ISSUE TITLE
Problem with array styles

### ISSUE THREAD

**Issue by christopheblin** [mapgears/ol3-google-maps#27]
As you may know, with open layers you are allowed to create an array of styles and to use it on a feature.

```
               var myStyle = [                            
                        new ol.style.Style({
                            image: new ol.style.Circle({
                                radius: 10,
                                fill: new ol.style.Fill({
                                    color: 'rgba(0,120,30,1)' //dark green
                                })
                            })
                            //!\ "file:///" images will block the printing of the map
                            //see http://simonsarris.com/blog/480-understanding-the-html5-canvas-image-security-rules
                            //image: new ol.style.Icon(({
                            //    anchor: [0.5, 1],
                            //    anchorXUnits: 'fraction',
                            //    anchorYUnits: 'fraction',
                            //    src: "images/anemometer_mono.png",
                            //    crossOrigin: 'anonymous' //you need this if you fetch images from another website
                            //}))
                        }),
                        new ol.style.Style({
                            image: new ol.style.Circle({
                                radius: 5,
                                fill: new ol.style.Fill({
                                    color: 'rgba(230,120,30,1)' //orange
                                })
                            })
                        })
                    ];

           var f = xxx;
           f.setStyle(myStyle);
```

this is causing an issue with ol3-gm, probably inside olgm.gm.createStyleInternal because you are not handling this case.

**Comment by adube** [comment]
Indeed.

I'm not sure yet, but I think Google Maps API only handles one style at a time: https://developers.google.com/maps/documentation/javascript/reference

If you have a suggestion or fix, I'd be happy to review a PR.

Thanks for you interest in OL3-Google-Maps.

**Comment by christopheblin** [comment]
I plainly admit that I have no knowledge of google maps :)

I have a good knowledge of OL and that's how I trace the problem to the styles array.

For the moment, I think the fix is to keep only the first element of the array

**Comment by adube** [comment]
I understand.  This is a reasonable limitation.

Would you be interested in creating a PR adding this limitation to the current list ? https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md

**Comment by christopheblin** [comment]
Updating wiki with PR https://github.com/mapgears/ol3-google-maps/pull/29

**Comment by christopheblin** [comment]
I will try to do the PR on the JS part.

**Comment by adube** [comment]
@christopheblin feel free to report any progress you may have done.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
