### ISSUE TITLE
Help bundling project for front end use

### ISSUE THREAD

**Issue by felixh85** [mapgears/ol3-google-maps#278]
Hi,
first this is not an issue but a request for help. I am totally new to node JS and I would really appreciate if someone could help me out generating a JS library file olgm.js for the current version. I have already googled this problem and tried a lot of stuff but I could not manage to generate the file I want. The OLGM should be integrated into an Apache Wicket Web Application.

**What do I want**: On the web page with the [examples](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/icon.html) there exist an olgm.js file containing the code of all individual files. This is the file I want. I took this file for a test and make my project work with this file. However, in the comment it says that this is based on version 0.20 and I want to work with the current version.

**What have I tried so far**:
I have installed nodeJS (I am working on a Windows OS) and installed the packages for ol and olgm as it is described in the README. Next, I installed Browserify and tried to use it on the src/olgm/index.js file but it did not work (I got a parsing error with respect to import and export).
I have tried to adapt the process displayed [here](https://openlayers.org/en/latest/doc/tutorials/bundle.html) and I was able to generate a test file. On this test file I tried to run browserify but I did not succeed so that I was not able to generate the desired file.

I would really appreciate if someone could help generating this file. Thank you in advance.

**Comment by geopamplona** [comment]
Hello,
I use the following package ol+webpack:

https://github.com/openlayers/ol-webpack

You can use this project as a basis for working with webpack and npm, and then integrate with olgm and run google layers

**Comment by felixh85** [comment]
Hi GeoPamplona,
Thank you for your answer. I checked out the ol+webpack package and tested it a little bit. However, I still did not manage to generate the file I need. I would really appreciate, if you could give me another hint.

**This is what I did:**
I downloaded the ol-webpack package and ran the test case inside with success. Next I added the olgm to the dependencies in the package.json and updated the main.js file with an example from the olgm example page. I ran this example with success, meaning without any error. However, when I started the index.html error, the map did not show because it could not find "google" even though I added the google api "<script async defer src="https://maps.googleapis.com/maps/api/js?key=key&v=3"></script>". Nevertheless, this is not what I want anyway, as I have to run/compile my code everytime I make changes. This is not applicable during the developement.
Next, I tried to run the webpack on the olgm. Thus, I went to the olgm folder and added the scripts, devDependencies and dependencies from the ol-webpack package.json to the olgm package.json and created a webpack.config.js pointing to the index.js as entry. This generated a bundle.js file. However, this file is only 150 kB big (the test file of the 0.2 version was over 500 kB) and seems to be incomplete. For example, at the command "olgm.interaction.defaults()" it returns that it does not know olgm (even though the js file is included).
Could you please give me a hint of what I am doing wrong. I would really appreciate your help. Thank you.

**Comment by geopamplona** [comment]
Hi, 

Try adding google apis before loading the bundle; this is important
With valid api key !
Follow steps from https://github.com/mapgears/ol3-google-maps#getting-started
you can follow the example:

```
import Map from 'ol/Map.js';
import GoogleLayer from 'olgm/layer/Google.js';
import {defaults} from 'olgm/interaction.js';
import OLGoogleMaps from 'olgm/OLGoogleMaps.js';
import View from 'ol/View';

var center = [-7908084, 6177492];

// This dummy layer tells Google Maps to switch to its default map type
const googleLayer = new GoogleLayer();

var map = new Map({
  // use OL3-Google-Maps recommended default interactions
  interactions: defaults(),
  layers: [
    googleLayer
  ],
  target: 'map',
  view: new View({
    center: center,
    zoom: 12
  })
});

var olGM = new OLGoogleMaps({map: map}); // map is the ol.Map instance
olGM.activate();
```
For quickly develop with webpack you can use Webpack web server (https://webpack.js.org/configuration/dev-server/ or https://github.com/webpack/webpack-dev-server)

I will try create a repo that integrate olgm + webpack + [load-google-maps-api](https://www.npmjs.com/package/load-google-maps-api)

**Comment by felixh85** [comment]
Hi GeoPamplona,
Thank you again for your feedback. I would appreciate if you could create repo which includes all the necessary libraries. This way, I hope I will be able to generate the required JS file. It will also probably help others like me who are inexpirienced with NodeJS.

As I was not getting anyware with my problem, I tried another approch which can be found [here](http://mikenunn.16mb.com/demo/ol5-google-demo.htm). I guess this is doing the exact same thing as olgm under the hood. However, I was able to generate a working example based on this, so that my issue is not that urgent anymore. Nevertheless, I want to integrate olgm in the future when I am able to generate the required JS file because it is much easier to handle.

Thanks again for your support.

**Comment by geopamplona** [comment]
Hi @felixh85,

I have created this example of integration between `olgm` + `webpack`
https://github.com/geopamplona/olgm-webpack
Its OK for me, and run corretly

Don't forget to change the apikey in `index.html`
Hope this can help you.

@adube do you think it is interesting to add this repo in some way in `olgm` readme?

**Comment by adube** [comment]
>@adube do you think it is interesting to add this repo in some way in olgm readme?

It would be interesting, yes.  Would you please provide a PR and refer this issue?  After landing it, we would close this issue.

Thank you very much!

**Comment by darkeagle76** [comment]
Hello,
I arrived here becose I'm looking for something quite similar :-).
I think that @felixh85 says is related to having a standalone "legacy" version of olgm that can be used in a "traditional" html page without using nodejs nor webpack.

@geopamplona: I think that what follows is interesting also for you. It seems that there are some build problems for the task "build-legacy" at least on a windows machine.

After downloaded the source code I found that the nodejs environment already have this "task" that, if my undestanding is correct, is called "build-legacy".

So I tried to perform a "build-legacy" compile of the project and I got some errors:
1) in the package.json "Task" section are used directly some commands that on a windows machine are not available (for example cp, rm). I added to my local check out the usage of the "shx" package
2) The old dependency "jsdoc 3.5.5" casuses an error with "requizzle" that seems not to be completely supported. To continue my building process I updated the jsdoc dependency to the 3.6.5 version.

After the above I had a correct exectution of "npm run build-legacy" with the wanted "olgm.js" file in the build folder, **anyhow this file already "bundles" some openlayers functions** and this could be a problem if someone would like to keep an external <script> reference to the ol.js legacy version.

I hope that the above could help others.
Thanks
D

**Comment by jerry1108** [comment]
@darkeagle76 : I  followed your guides to build and got the olgm.js successfully. However, there were some problems while I added polygon/point vector layer to the map instance. The layer can't fixed on the goolgle map while I zoom in/out or drag it but it works while I switch the base layer to OSM. 
I aslo used the olgm-webpack geopamplona provided to integrate my codes to compile and got the bundle.js, but it still had the same issue.
@adube So I think the "legacy" version can't work properly and there are two choices to achieve the goal: use the ES6 module to develop or if someone wants  the "legacy" version, you can refer to the [sample ](http://mikenunn.16mb.com/demo/ol5-google-demo.htm) that @felixh85 provides to implement the function.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
