### ISSUE TITLE
Support for OpenLayer 6+

### ISSUE THREAD

**Issue by mstenta** [mapgears/ol3-google-maps#282]
OpenLayers 6 removes the `LayerType.js` file that we reference in `src/olgm/layer/Google.js`: https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/layer/Google.js#L4

This results in an error when using this with Webpack:

```
ERROR in ./node_modules/olgm/layer/Google.js
Module not found: Error: Can't resolve 'ol/LayerType.js' in '/usr/src/app/node_modules/olgm/layer'
 @ ./node_modules/olgm/layer/Google.js 4:0-40 44:16-25
 @ ./src/instance/methods/google.js
 @ ./src/instance/instance.js
 @ ./src/main.js
```

**Comment by mstenta** [comment]
The update required for this is pretty simple. I will open a PR.

This raises a question though: how do we want to handle the OL version compatibility in `package.json`. Currently it is:

`"ol": "^5.0.0 || ^4.0.0"`

I think we'll want to either add `^6.0.0` to that, or replace it entirely. However, I'm not sure if the change we need to make for 6 will be backwards compatible with 4 and 5.

**Comment by mstenta** [comment]
FYI here is the commit that removes `LayerType.js` from OpenLayers upstream: https://github.com/openlayers/openlayers/commit/ca5b0c63a582687cd847658c7d503b73b1fd4eb4

**Comment by mstenta** [comment]
Opened a PR that fixes the issue and adds `^6.0.0` to `package.json`: #283

**Comment by mstenta** [comment]
There might be more to this... Travis tests on that PR failed. And I'm getting this error in console when I try to switch to a Google layer: `TypeError: layerRenderer is null`

**Comment by adube** [comment]
Just for the record, I agree with switching to 6.0.0 entirely.

**Comment by mstenta** [comment]
Thanks @adube! That will make it easier.

**Comment by mstenta** [comment]
Getting closer...

I traced the failing tests to the following condition in `activateGoogleMaps_()` in `src/olgm/herald/Layers.js`:

```
  activateGoogleMaps_() {

    const center = this.ol3map.getView().getCenter();
    if (this.googleMapsIsActive_ || !this.ol3mapIsRenderered_ || !center) {
      return;
    }
```

Specifically, it's the presence of the `!this.ol3mapIsRenderered_` that causes the tests to fail. Removing that middle condition allows the tests to pass.

It looks like `!this.ol3mapIsRenderered_` is being set by this block of code in the constructor of the same class:

```
    // some controls, like the ol.control.ZoomSlider, require the map div
    // to have a size. While activating Google Maps, the size of the ol3 map
    // becomes moot. The code below fixes that.
    const center = this.ol3map.getView().getCenter();
    if (!center) {
      this.ol3map.getView().once('change:center', () => {
        this.ol3map.once('postrender', () => {
          this.ol3mapIsRenderered_ = true;
          this.toggleGoogleMaps_();
        });
        this.toggleGoogleMaps_();
      });
    } else {
      this.ol3map.once('postrender', () => {
        this.ol3mapIsRenderered_ = true;
        this.toggleGoogleMaps_();
      });
    }
```

Trying to understand that now... any input is welcome! :-)

**Comment by mstenta** [comment]
> And I'm getting this error in console when I try to switch to a Google layer: `TypeError: layerRenderer is null`

Decided to dig into this first, and traced it to the fact that the layer type was removed, which meant OpenLayers didn't know what layer renderer to use. I was able to fix it by adding a `createRenderer` method to the `GoogleLayer` class, which I copied directly from the `TileLayer` class: https://github.com/openlayers/openlayers/blob/v6.1.1/src/ol/layer/Tile.js#L32

So then, instead of doing that, I tried simply making `GoogleLayer` extend from `TileLayer`, instead of from `Layer`. And that also fixed it (that class inheritance is not much different).

I'm not sure if that's the right approach, though, since the Google layers are not exactly "tile" layers.  They are tile-based, but they aren't actually being added to the map as tiles in the same way (as I understand it).

I tried looking through what the other renderer options were, but couldn't find any better choice, unless we wanted to create our own renderer class that extends from the base `LayerRenderer` - but I don't know if that's necessary.

FWIW the Google layers seem to be working pretty well now!

**Comment by mstenta** [comment]
Force pushed my `ol6` branch to include the `TileLayer` change and break up the commits.

Now back to the failing tests...

**Comment by mstenta** [comment]
Oh! Switching to `TileLayer` fixed the failing tests too! :tada: 

So I think this is ready for review!

PR: #283

**Comment by adube** [comment]
#283 has been merged. OL6 is now supported.  Thanks a lot @mstenta for taking care of this.
