### ISSUE TITLE
Restore ol-layerswitcher example

### ISSUE THREAD

**Issue by mstenta** [mapgears/ol3-google-maps#287]
Now that #37 is resolved, I think we can restore the layerswitcher example that used to be included in this library. It was "archived" (moved to `examples/archived`) back in August 2018 with this commit: https://github.com/mapgears/ol3-google-maps/commit/cc62e0e8e9a848fe44bde8799812471467e28c56

I have it working again and will open a PR shortly...

**Comment by mstenta** [comment]
Here is a pull request ready for review: https://github.com/mapgears/ol3-google-maps/pull/288

It updates to the latest version of `ol-layerswitcher`. It also adds the layerswitcher CSS to the example. In order to do this, I needed to add `css-loader` and `style-loader` packages so that I could use `import` to add CSS.

**Comment by adube** [comment]
Fixed in #288
