### ISSUE TITLE
Cannot show the satellite image properly

### ISSUE THREAD

**Issue by HKBULIB** [mapgears/ol3-google-maps#292]
Only a small square of the satellite image is shown.  What is the problem?

URL:
http://digital.lib.hkbu.edu.hk:3000/

**Comment by adube** [comment]
Have you tried setting an API key?

https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by adube** [comment]
No, that's not it.  Resizing the browser window solves the issue.

Are you using the latest version of OLGM?  If not, try to upgrade to see if it solves the issue.  Otherwise, this is a bug.

**Comment by HKBULIB** [comment]
Thank you for your reply.  I will try to use the latest version of OLGM.  Hope this issue can be solved.

**Comment by HKBULIB** [comment]
// Ol3-Google-Maps. See https://github.com/mapgears/ol3-google-maps/
// License: https://github.com/mapgears/ol3-google-maps/blob/master/LICENSE
// Version: v0.20.0

We try to use version v0.20.0 of ol3gm.js, but the issue still exists.  Thank you for your attention.

URL
http://digital.lib.hkbu.edu.hk:3000/

**Comment by adube** [comment]
The version 0.20.0 is the last version that provided a bundle, but it's not the latest version.  See: 

https://github.com/mapgears/ol3-google-maps/releases

OLGM no longer provides a bundle.  Read more about it here and how to use the latest version:

https://github.com/mapgears/ol3-google-maps/pull/257#issuecomment-530824025

HTH

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
