### ISSUE TITLE
Vector layer and Google layer position on pan

### ISSUE THREAD

**Issue by martinmcneela** [mapgears/ol3-google-maps#293]
I have a very simple example built using react and using olgm. The example uses a piece of state to toggle the visibility of an Open Street Map layer and a Google layer. Along-side these two layers is a vector feature layer with a polygon drawn on it (over Trafalgar square) the should always be visible. With the Google layer visible (and the watchers set to true), the feature does not appear on the desired location. Follow these steps in the sandbox to see the issue:

 - Go to public/index.html and paste in a Google Maps API key on line 5
 - Pan the map, the Polygon will stay on Trafalgar square
 - Click the `Toggle layers` button in the Browser panel
 - The Google layer should be displayed
 - Pan the map, the Polygon will not stay on Trafalgar square

I have the following sandbox to help me explain this issue: https://codesandbox.io/s/openlayers-react-olgm-jl0dy

Not sure if I am missing something.

**Comment by martinmcneela** [comment]
Ok doing a little more digging around with this one I have created another sandbox, removing react from the equation. In the sandbox, `index.js` uses the projection `EPSG:27700` and DOES the issue outlined above, `index2.js` uses the Openlayers default projection and DOES NOT have the issue outlined above.

https://codesandbox.io/s/openlayers-5-google-layer-iqwqb (again the Google maps key will need to be updated in index.html)

Is there a way I can handle the different projection? Or is this something that will only work with the default projection?

**Comment by adube** [comment]
Hello @martinmcneela 

When using Google Maps, you have to use the Mercator projection (i.e. EPSG:3857), which is also the one used by default in OpenLayers.  The map tiles provided by Google Maps use that projection and there's no way to use any other ones.

HTH

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
