### ISSUE TITLE
Google layers do not show when grouping base layers using Layerswitcher

### ISSUE THREAD

**Issue by jllodra** [mapgears/ol3-google-maps#294]
When grouping base layers using `ol.group.layer`, the google layers do not show (they show on the layerswitcher ui, but when selected they are not visible).

I have been following both official examples.

**How to reproduce**

https://github.com/mapgears/ol3-google-maps/blob/master/examples/layerswitcher.js

Try adding a group of layers with the 2 layers (googleLayer and osmLayer) in it.

**Layerswitcher official example for reference**

https://github.com/walkermatt/ol-layerswitcher/blob/master/examples/layerswitcher.js

----

Might be related to #285

**Comment by adube** [comment]
Thanks for reporting this issue.  Feel free to provide a patch to fix this issue.  Also, it would be nice to include a change to the layerswitcher example to show that, with a fix, it would then work as expected.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
