### ISSUE TITLE
GoogleLayer crossOrigin

### ISSUE THREAD

**Issue by wussup** [mapgears/ol3-google-maps#297]
Hello,

is there any way to add crossOrigin: anonymous option to Google Layer?

I want to export map like [here](https://openlayers.org/en/latest/examples/export-map.html) and google layer is not visible.

**Comment by adube** [comment]
I'm not sure but I think it's not legal to do that because of the Google Maps APIs Terms of Service.  See https://developers.google.com/maps/terms-20180207

>10.5 Intellectual Property Restrictions.
>c. No use of Content outside the Service.
>You will not use any Content outside of the Service except as expressly permitted to do so in Subsection (d). For example, you will not export or save the Content to a third party’s platform or service.

**Comment by wussup** [comment]
> I'm not sure but I think it's not legal to do that because of the Google Maps APIs Terms of Service. See https://developers.google.com/maps/terms-20180207
> 
> > 10.5 Intellectual Property Restrictions.
> > c. No use of Content outside the Service.
> > You will not use any Content outside of the Service except as expressly permitted to do so in Subsection (d). For example, you will not export or save the Content to a third party’s platform or service.

Yes, I know it, but I don't want to export or save "the Content" as tiles or something else, I would like to print a map using my template (like Ctrl+P works).

**Comment by luciman** [comment]
@wussup the export map from the openlayers example do not work with ol3-google-maps. you can use html2canvas with useCORS: true
take a look on https://stackoverflow.com/questions/24046778/html2canvas-does-not-work-with-google-maps-pan/24281734#24281734 and adapt it for your div
works like a charm

**Comment by wussup** [comment]
> @wussup the export map from the openlayers example do not work with ol3-google-maps. you can use html2canvas with useCORS: true
> take a look on https://stackoverflow.com/questions/24046778/html2canvas-does-not-work-with-google-maps-pan/24281734#24281734 and adapt it for your div
> works like a charm

Thank you very much! Working like a charm!

```
import html2canvas from "html2canvas";

let generateMapBase64 = function (callback) {
    html2canvas(document.querySelector(".vl-map>div"),
        {
            useCORS: true
        }).then(canvas => {
            if (callback)
                callback(canvas.toDataURL());
        });
};

export { generateMapBase64 };

export default { generateMapBase64 };
```
