### ISSUE TITLE
Uncaught TypeError: a.Yf is not a function with OL3-Google-Maps v0.15.0

### ISSUE THREAD

**Issue by planck4** [mapgears/ol3-google-maps#299]
Hey guys,

I'm using OL3-Google-Maps v0.15.0 as our project is on OL 4.2.0. I read that version already includes OL. Our application already includes OL 4.2.0 Is there a way that I can use the already available OL?
Also, we are adding the Google maps script dynamically.  I tried loading ol3gm.js dynamically after Google maps. It gets loaded but I get an error with the following code:
`const olGM = new olgm.OLGoogleMaps({map: map})`
`Uncaught TypeError: a.Yf is not a function`
I tried looking in the source code and think that it refers to `this.gmapEl_ = gmap.getDiv();` in ol3gm.js file.
I tried to use ol3gm-debug.js but I get the error that namespace ol is already defined.
Here I have a little confusion. The minified file does not throw this error. Doesn't the minified file include OL 4.2.0 as well?
Here is the code that I used
```
function googleCallback () {  // This runs after Google API is loaded
      const script = document.createElement('script');
      script.src = './assets/js/ol3gm.js';
      script.type = 'text/javascript';
      document.head.appendChild(script);
      setTimeout(() => { // Give some time for ol3gm to load, otherwise get an error
        const googleLayer = new olgm.layer.Google();
         map.addLayer(googleLayer);
         const olGM = new olgm.OLGoogleMaps({map: map}); // map is the ol.Map instance
         olGM.activate();
      }, 5000);
}
```

Any help is appreciated.

**Comment by adube** [comment]
>I'm using OL3-Google-Maps v0.15.0 as our project is on OL 4.2.0. I read that version already includes OL. Our application already includes OL 4.2.0 Is there a way that I can use the already available OL?

To my knowledge, there was no way of loading an other OL other than the one already packaged in the minimized version back then.

>Also, we are adding the Google maps script dynamically. I tried loading ol3gm.js dynamically after Google maps. It gets loaded but I get an error with the following code: ....

Loading OLGM after Google Maps is required for it to work.

**Comment by planck4** [comment]
Yes, I'm loading OLGM after Google maps, but still getting that error. And any idea why I'm getting the namespace already declared error in ol3gm-debug.js and not in ol3gm.js?

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
