### ISSUE TITLE
Google map and WMTS layer zoom desync with rapid scrolling

### ISSUE THREAD

**Issue by FrankyBoy** [mapgears/ol3-google-maps#301]
Hi!

I am working on a google map with a custom overlay from a WMTS source. The code looks basically like this gist: https://gist.github.com/FrankyBoy/f5cbbd1ef5a697820832d252f7d9dc3f.

I've noticed that when I scroll rapidly in and out, the two layers "detach" from each other, and zoom levels do not fit any more. To me it seems the reason is that the Google layer does not follow the actual zoom inputs while playing its (annoying) animation. 

With other layers (eg. an OSM WMTS source) in the background, these layers stick together like intended, so it seems to be a problem specific to this library.

Hope somebody can help because this is actually kinda breaking a product for us :/

Cheers :)

**Comment by FrankyBoy** [comment]
Edit: lol ... of course I googled before and didn't find anything, then googled again and now I got a match 🤦 . #216 already talks about this.

**Comment by FrankyBoy** [comment]
Reopening based on Licians inputs.

**Comment by luciman** [comment]
@FrankyBoy 

`let olGM = new OLGoogleMaps({
  map: this.map,
  watch: {
    tile: true
  }
});`

or
`let olGM = new OLGoogleMaps({
  map: this.map
});`
doesn't solve your problem ?

**Comment by FrankyBoy** [comment]
If I do that then I seem to lose my overlay, though maybe that got to do with the way I add my layers. I.e. I'm actually inserting layers dynamically, which might be a bad idea for olgm. Will try what happens if I rebuild the layers entirely each time.

**Comment by zach-sim-dc** [comment]
I've been having a similar issue on my side with I believe is related.

If I zoom in using the +/- buttons, while the animations in both the google and an openlayers overlay layer, they appear to snap correctly into place when the animations are over.

If instead I zoom using a mousewheel the layers start desyncing.

Edit: My issue appears to be due to fractional zooming. If I enable constrainResolution it is resolved.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
