### ISSUE TITLE
Google Maps is displayed over the top of tile layers in Angular

### ISSUE THREAD

**Issue by tinyg** [mapgears/ol3-google-maps#304]
When using Angular and the "olgm" npm package, the Google Maps layer seems to always appear above all other tile layers regardless of z-index or other settings.

Steps to reproduce:

- Create new angular project with "ng new tmp"
- Add OpenLayers with "npm install ol"
- Add OLGM with "npm install olgm"
- Setup as per instructions [here](https://www.npmjs.com/package/olgm) 
- Replace the app.component contents with the sample code from [Simple](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/simple.html)
- Add a tile WMS layer as per [Tiles](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/tiles.html)

Attached is a sample project. To use (assuming you have node / npm and angular CLI installed):

- unzip to a folder
- open terminal / command prompt
- run "npm install"
- run "ng serve"
- open url as per output from "ng serve".

Expected result:

- Google backdrop with WMS tile layer over the top

Actual result:

- Google map displayed over the top of the WMS layer (see screenshot)

[test-project.zip](https://github.com/mapgears/ol3-google-maps/files/4851589/test-project.zip)
![olgm](https://user-images.githubusercontent.com/8664926/86123498-f4dfaf80-bb1c-11ea-90c9-93f9ee94020b.png)

**Comment by adube** [comment]
Thanks for the nicely detailed issue and for your interest in olgm!

Feel free to contribute a patch that solves this issue.

**Comment by tinyg** [comment]
Hmm - not really sure why it's happening - I had a go at playing around with the divs in the rendered page but didn't seem to be able to make much headway. Happy to have a go if you can suggest where I would even start...

**Comment by adube** [comment]
@tinyg I went and checked the "wms" example while running the local dev env. for olgm (i.e. ran `npm run serve-examples`, then visited http://localhost:8080/wms.html) and I could see the issue in action from there.  So, there must have been a change in the lastest version of Google Maps API that broke something.

In other words, the issues doesn't seem to be related to the fact that Angular is used.  You can reproduce it without it.

I'd start by running the example and debug the code from there.  I'd also try to look for potential changes to the Google Maps API that could be suspect to this no longer working.  These are my recommendations.

HTH,

Alexandre

**Comment by tinyg** [comment]
Just an update on this, we can see that this issue is actually not present in the trunk code but is present in 1.6. We're wondering when a new patch might be released to npm?

Also it seems like this is broken again in later versions of OpenLayers - OL 6.1.1 works ok but later does not. Looks like OL added an additional API to TileSource which the OLGM wrapper does not provide.

**Comment by adube** [comment]
>Just an update on this, we can see that this issue is actually not present in the trunk code but is present in 1.6. We're wondering when a new patch might be released to npm?

I can publish a new release.

>Also it seems like this is broken again in later versions of OpenLayers - OL 6.1.1 works ok but later does not. Looks like OL added an additional API to TileSource which the OLGM wrapper does not provide.

Would you please provide a patch for this? I'd be happy to review/test it.

Thanks

**Comment by rajsync** [comment]
Please test and approve the patch for the ol latest breaking changes. https://github.com/mapgears/ol3-google-maps/pull/314
 Error received without fix
![Capture](https://user-images.githubusercontent.com/71109719/92852586-3dc3b680-f432-11ea-9433-e6e5505e8cf1.PNG)
After fix
![Capture1](https://user-images.githubusercontent.com/71109719/92852753-677cdd80-f432-11ea-9904-98d7d32b75ea.PNG)

Please do a build and release a new version

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
