### ISSUE TITLE
Interaction not working

### ISSUE THREAD

**Issue by sudarshanuprety42** [mapgears/ol3-google-maps#309]
With olgm+openlayer 6, Interaction on map(zoom, scroll) not working properly. Can anyone help

**Comment by adube** [comment]
I went and quickly checked the examples with OL v6.4.3 (latest) and the interactions seemed to work fine on my end.

Would you please try running the examples locally and see if they work for you?  Maybe that could help you see if something is not configured correctly on your end.

1. clone the repository
2. run `npm install`
3. run `npm run serve-examples`
4. visit http://localhost:8080/concept.html

HTH

**Comment by geopamplona** [comment]
I upload my example using latest OL, It run correctly, without fails.

https://github.com/geopamplona/olgm-webpack

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
