### ISSUE TITLE
Mobile Performance problem with OL3 and Google Maps

### ISSUE THREAD

**Issue by fatihalp** [mapgears/ol3-google-maps#32]
It's perfect extension for OL3 thanks a lot! But when I navigate with mobile browser it's not smooth like OL3. Is there anything to do for it?

http://dev5.mapgears.com/ol3-google-maps/examples/simple.html

Check it from offical demo

**Comment by adube** [comment]
Hi,

I see can see a difference, but you'll need to be more specific.  What type of mobile device are you using ?  What OS ?  What are the exact differences you're experiencing ?  You description is currently too vague.

Any contribution or fix would be welcome.  I'd be happy to review a PR if you provide one.

Thanks for your interest in OL3-Google-Maps !

**Comment by fatihalp** [comment]
Hi Alexandre, thanks for your fast reply! :)
I've tried different models of Android (6.0), iOS (9.1) and tablets
Pinch (in-out) is not working for either of them. Although in OL3 is working.

**Comment by adube** [comment]
Hi,

For me, the pinch in and out action end up making the map zoom in and out, but while doing so the map doesn't budge. That's normal.  It's a limitation.  Let me explain.

OL3-Google-Maps puts an ol3 map on top of google-maps.  The interactions are all managed by ol3, not google maps.  So, while pinching, ol3 view center/resolution are not changing.  It only occurs when you stop pinching.  The Google Maps map is only updated when the center/resolution changes, so it makes it appear as if nothing was happening while pinching, but in reality it does.

I currently don't know a way to make the Google Maps map follow the OL3 map while it's being interacted, nor I think it's a good idea.  It's something we have to live with in the end.

Just to make sure, would you please see if the map zooms in/out while pinching for you ?

**Comment by fatihalp** [comment]
@adube Just you explained it's appear when event is finished.

**Comment by adube** [comment]
I'm closing this one as I don't think we'll fix it.
