### ISSUE TITLE
Errors using the make command

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#33]
When I run `make`, i get a help page with a list of commands, e.g. `make dist`. When I try `make dist` which does _"Create a distribution for the library (dist/ol3gm.js)"_ (from the help page), the command fails:

```
$:~/../ol3-google-maps$ make dist
(cd ol3 && npm install && node tasks/generate-externs.js build/ol-externs.js)
# ... npm install, populating node_modules ...
module.js:339
    throw err;
    ^

Error: Cannot find module '/.../ol3-google-maps/ol3/tasks/generate-externs.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
make: *** [ol3/build/ol-externs.js] Error 1
```

And quite right, `ol3/tasks/generate-externs.js` does not exist. In fact, the `ol3` folder is empty.

Am i doing something wrong here, or is the make tools broken?

**Comment by adube** [comment]
Try tu run `git submodule update --init --recursive`, then retry.

Please, let me know if that works for you.  I would update the README accordingly.

**Comment by fipp** [comment]
Thank you! Yes I realized after a while that there were something special about the ol3 folder. I didn't know what submodules was at that time. Learning this, I tried to do a `git clone https://github.com/openlayers/ol3` (standing in the ol3-google-maps repository) but then `git status` displayed `modified:   ol3 (new commits)`. And trying to do a `make dist` with these new commits in the ol3 repository led to this error:

```
ERR! compile ol3/build/ol-externs.js:3743: ERROR - mismatch of the getSource property type and the type of the property it overrides from superclass ol.layer.Layer
```

Then i cleaned up (`rm -rf ol3; git checkout ol3`) and ran your command - `git submodule update --init --recursive`. This seems to clone the `ol3` repository and check out the commit the `ol3-google-maps` repository is pointing to. Now `make dist` does not produce an error, however it never finishes, it gets stuck at this point (last log entry):

```
Copying extracted folder /var/folders/_f/47vyjfs52jsc0cf2y59_my_c0000gn/T/phantomjs/phantomjs-1.9.7-macosx.zip-extract-1450772524744/phantomjs-1.9.7-macosx -> /../ol3-google-maps/ol3/node_modules/phantomjs/lib/phantom
```

This seems to be a Mac issue. I've found what seems to be the exact same problem referenced here: https://github.com/filamentgroup/grunt-criticalcss/issues/33

**Comment by fipp** [comment]
By the way, my latest issue (the "copying extracted folder" for phantomjs) seems to be the same as this issue: https://github.com/filamentgroup/grunt-criticalcss/issues/33

**Comment by fipp** [comment]
Hope I'm not complicating the issue too much, but I tried to fire up a Ubuntu VM (Vagrant/VirtualBox with image ubuntu/trusty64), did `apt-get update`, `apt-get upgrade` and `apt-get install git nodejs npm`. Then I cloned ol3-google-maps, initialized the ol3 submodule and did a `make dist` (not with root) but it did also fail, but with an error this time:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ make dist
(cd ol3 && npm install && node tasks/generate-externs.js build/ol-externs.js)
...
npm http 200 https://registry.npmjs.org/nan/-/nan-1.0.0.tgz

> ws@0.4.32 install /home/vagrant/ol3-google-maps/ol3/node_modules/closure-util/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/ol3-google-maps/ol3/npm-debug.log
npm ERR! not ok code 0
make: *** [ol3/build/ol-externs.js] Error 1
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ 
```

Last 10 lines of `ol3/npm-debug.log`:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ tail -n 10 ol3/npm-debug.log 
25156 error     <npm-@googlegroups.com>
25157 error System Linux 3.13.0-68-generic
25158 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
25159 error cwd /home/vagrant/ol3-google-maps/ol3
25160 error node -v v0.10.25
25161 error npm -v 1.3.10
25162 error path /home/vagrant/tmp/npm-11170-UbJXFJxu/1450777757393-0.4532611295580864/package/index.js
25163 error code ENOENT
25164 error errno 34
25165 verbose exit [ 34, true ]
```

Just like FYI :)

**Comment by adube** [comment]
Mmm, not sure what the issue here is yet.  I'll have to try with a fresh VM as well and attempt to follow the readme to see if there's a step that has been forgotten.

I won't have the time to try this in the next couple days.  Here's a wild guess you could do in the meantime: delete the `node_modules` from the root directory and also the one in `ol3`, then try again.  If you're lucky, that could solve the issue.

I'll talk to you soon.

**Comment by fipp** [comment]
No biggie. I just downloaded the already compiled files from one of the examples, and I'm using them until I manage to compile correctly.

**Comment by adube** [comment]
All right.

FYI, you can download the source code from the official releases here: https://github.com/mapgears/ol3-google-maps/releases.

**Comment by fipp** [comment]
Hi!

Have you had any chance to look any more to this? I tried deleting the npm_modules folder in `ol3-google-maps` as well as in the `ol3` subfolder, then running `make dist` again, without success :/

**Comment by adube** [comment]
Not yet.  I'll keep you in touch.

**Comment by adube** [comment]
Just to let you know: I've tried twice in the past few weeks starting with a fresh VM and so far I've not been able to make it work either.  I'll try to get some help from the ol3 developers as I'm currently at a dead end in my searches.   I'll keep you in touch.

**Comment by fipp** [comment]
Thank you for the update Alexandre!

**Comment by adube** [comment]
Here's more news on this front.  With the help of a core dev of ol3, I was able to make the build work.  I'll start over in order to write clean steps on how to make it work from scratch.  If you want, I could also share the end result, i.e. a VirtualBox VM.  You'd be able to clone your own ol3-google-maps fork in it and use it to do your contributions.

What I was missing in my VMs: memory.  Turns out 512mg of mem. is not enough.  I set it to 4092 instead and everything worked smoothly from there on.  I'll keep you in touch.

**Comment by fipp** [comment]
If it's not too much of a hassle to you, sharing the VM sounds like a good idea to get going!

**Comment by fipp** [comment]
For the record I tried to boot a ubuntu/trusty64 VM with 4GB RAM and 2 cores with VirtualBox and Vagrant. What I did:

```
    1  sudo apt-get -y update; sudo apt-get -y upgrade
    2  curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
    3  sudo apt-get install -y nodejs git build-essential
    4  git clone https://github.com/mapgears/ol3-google-maps.git; cd ol3-google-maps; git submodule update --init --recursive
    5  make dist
    6  make dist
    7  sudo npm install -g closure-util
    8  make dist
    9  make dist
   10  make dist
   11  make dist
```

You'll see I did `make dist` multiple times. After the first invocation, I aborted manually because the script seemed stuck at this point:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ make dist
...
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2-extract-1453311207942/phantomjs-1.9.7-linux-x86_64 -> /home/vagrant/ol3-google-maps/ol3/node_modules/phantomjs/lib/phantom
```

At the second invocation, I needed to install `closure-util`:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ make dist
...
> openlayers@3.10.1 postinstall /home/vagrant/ol3-google-maps/ol3
> closure-util update

sh: 1: closure-util: not found
```

Then on the 3rd and 4th, I got this:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ make dist
...
> openlayers@3.10.1 postinstall /home/vagrant/ol3-google-maps/ol3
> closure-util update

Trouble generating info: Failed to parse output as JSON: {
  "symbols": [
    {
...
```

Then, seemingly I got this from here on out :)

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ make dist
...
> openlayers@3.10.1 postinstall /home/vagrant/ol3-google-maps/ol3
> closure-util update

mkdir -p dist/
node build/build.js build/ol3gm.json dist/ol3gm.js
info ol3-google-maps Parsing dependencies
info ol3-google-maps Compiling 39 sources
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
make: *** [dist/ol3gm.js] Error 1
```

Confusing :D

**Comment by adube** [comment]
@fipp I got stucked at that place too.  I tried upgrading ol3 to v3.12.1 (I also tried v3.13.0) and that issue is gone.  I'm now facing other kinds of issues, which I'm currently asking for help on the ol3-dev mailing list.  I'm looking forward to receive an answer from the ol3 devs.

Bottom line, we'll have to upgrade the ol3 to a newer version within ol3-google-maps. I'll take care of it after I receive help from the ol3 devs.  I'll keep you in touch.

**Comment by fipp** [comment]
Hooray! I got it to work using OpenLayers v3.10.1 which ol3-google-maps points to. I figured that I might try to install java after looking at the `spawn java  ENOENT` error from above. I installed Java 8. Afterwards, I destroyed the VM and re-created one (ubuntu/trusty64 with vagrant/VirtualBox). After a couple of hours of trying and failing, I came up with what seems to be a working set of steps to build without errors (kind of) or re-tries:

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get -y update; sudo apt-get -y upgrade
sudo apt-get install -y nodejs git build-essential oracle-java8-installer
sudo apt-get install oracle-java8-set-default
sudo npm install -g closure-util
git clone https://github.com/mapgears/ol3-google-maps.git
cd ol3-google-maps
git submodule update --init --recursive
make dist # Do not abort when stuck, read comment below
```

**Important**: Do not abort the script when `make dist` gets stuck at this point:

```
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2-extract-1453369363004/phantomjs-1.9.7-linux-x86_64 -> /home/vagrant/ol3-google-maps/ol3/node_modules/phantomjs/lib/phantom
```

Instead, open up a new terminal window and run `make dist` from there as well. Now it compiles and `./dist/ol3gm.js` is populated:

```
vagrant@vagrant-ubuntu-trusty-64:~/ol3-google-maps$ head ./dist/ol3gm.js
// Ol3-Google-Maps. See https://github.com/mapgears/ol3-google-maps/
// License: https://github.com/mapgears/ol3-google-maps/blob/master/LICENSE
// Version: v0.3-18-g0bc0d55
```

The stuck `make dist` execution from the first terminal window can now be aborted, and any subsequent runs of `make dist` now seem to go just fine. 

I've tried this three times now (destroy and re-create vm and re-run the steps) and it seems consistent. Could be pure luck though. I suspect that something in the make/build script does things in parallell, and that this can screw things up from time to time.

**PS:** I tried the forementioned method with OpenLayers 3.12.1 and 3.13.0 as well, but here I still get compilation fails:

v3.12.1 (https://github.com/openlayers/ol3/commit/863cc1bae3be1a5a7d9d99f26dfc8a5c6450e3e6)

```
info ol3-google-maps Compiling 39 sources
ERR! compile ol3/build/ol-externs.js:3743: ERROR - mismatch of the getSource property type and the type of the property it overrides from superclass ol.layer.Layer
ERR! compile original: function (this:ol.layer.Vector): (null|ol.source.Vector)
ERR! compile override: function (this:ol.layer.VectorTile): (null|ol.source.VectorTile)
ERR! compile ol.layer.VectorTile.prototype.getSource = function() {};
ERR! compile ^
ERR! compile 
ERR! compile 
ERR! compile 1 error(s), 0 warning(s), 96.4% typed
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
make: *** [dist/ol3gm.js] Error 1
```

v3.13.0 (https://github.com/openlayers/ol3/commit/ccdb189e774db75b04b62e856fc813475523acba)

```
info ol3-google-maps Compiling 39 sources
ERR! compile ol3/build/ol-externs.js:3391: ERROR - Bad type annotation. Unknown type proj4
ERR! compile  * @param {proj4} proj4
ERR! compile            ^
ERR! compile 
ERR! compile 
ERR! compile 1 error(s), 0 warning(s)
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
make: *** [dist/ol3gm.js] Error 1
```

Seems like ol3gm.js is not up-to-date with OpenLayers >= 3.12.1 requirements?

**Comment by adube** [comment]
@fipp Yeah, those are the issues I hadn't talked about yet.  I plan to upgrade to the master version of ol3, i.e. past 3.13.0, as the above are being fixed as we speak in the ol3 core source code.  I expect these to be fixed by the end of the week. I'll keep an eye on that and once the fixes are made in ol3, I plan to upgrade to master in ol3-google-maps.  That should fix the issue you have been having.

Let's keep this ticket open for now anyway.  This is an excellent one, btw.  The steps you describe could become useful for someone someday.  Thanks for that!

I'll keep you in touch.

**Comment by adube** [comment]
With #43 now fixed, the installation procedure is ready to be updated.  I'll do this right away.

**Comment by adube** [comment]
#45 includes better installation procedure, i.e. steps for developers willing to contribute patches or new features to OL3-Google-Maps.

With this, you should no longer have any issues with the `make` command.  I'm closing this now.  Thanks for reporting this, @fipp.
