### ISSUE TITLE
Hiding layers when Google Maps layer is zooming  

### ISSUE THREAD

**Issue by sandeepincode** [mapgears/ol3-google-maps#330]
Hi there,

I am using `ol3-google-maps` with `ol`.

The issue is whenever the google maps layer zooms in or out the vector title layer(s) loads into position before the Google maps layer has completed the zoom animation. 

The solution I came to was to hide the vector title layer(s) using `setVisible` and map/view events.

```
  // WHEN MAP ZOOMS - remove all but google
  map?.getView().on('change:resolution', () => ShowLayers(false));

  // WHEN ZOOM IS COMPLETE
  map?.on('rendercomplete', ShowLayers(true));

```

This works, however, it is not great as it is inconsistent whenever zooming.
Is there anyway to get access to the google maps event and use something like `idle`?

**Comment by adube** [comment]
I haven't look too deep at the issue you're having but, as a tip, know that from OLGM you can access the GoogleMaps object here:

https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/OLGoogleMaps.js#L151

**Comment by sandeepincode** [comment]
Would that be something similar to the below? and would I pass the `google` into the listener or the `initialMap`

```
 const google = new GoogleLayer({
      mapType: mapView,
    });
    const initialMap = new Map({
      ...mapRef?.current && { target: mapRef.current },
      layers: [google],
      view: new View({
        center: olProj.fromLonLat([0, 51.5]),
        zoom: 15,
      }),
    });
const olGM = new OLGoogleMaps({ map: initialMap });
.
.
.
map?.getView().on('change:resolution', function() {
    olGM.getGoogleMapsMap().event.addListenerOnce(
        ???, 
        'idle', 
        function() {
            ShowLayers(true)        
          }
    );
   ShowLayers(false)
});

```

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
