### ISSUE TITLE
olgm 1.7.1 not working with openlayer 7.1.0

### ISSUE THREAD

**Issue by tombags** [mapgears/ol3-google-maps#334]
I am trying to use the latest version of olgm (1.7.1) with the latest version of OpenLayers (7.1.0). 

Creating an olgm Google Layers fail at run time with error:
 Uncaught TypeError: Class constructor TileLayer cannot be invoked without 'new'  at new GoogleLayer2 (Google.js:26:5)

This can be replicated using the simple example code from the examples directory and changing the OpenLayers dependency to version 7.1.0

I suspect this error is due to differences in the build process for the OpenLayers and olgm npm packages.  Prior to OpenLayers version 7.0.0 OpenLayers transpiled its code to es5.  Starting at 7.0.0 OpenLayers no longer transpiles its code to es5 and leave its code as is.  The olgm package is still transpiled in the build-package step.   The error message above is related to using older es5 style constructors in a child class that has a parent class with the newer es6 style syntax.

**Comment by adube** [comment]
Hello @tombags.  Would you be interested in contributing a fix for this issue?  Thanks for reporting this.

**Comment by tombags** [comment]
@adube, I will see if I can come up with a fix

**Comment by boomdrak** [comment]
@adube is ol3-google-maps  abandoned?

**Comment by adube** [comment]
> @adube is ol3-google-maps abandoned?

It's not abandoned, but gets less contributions/attention than in the past years.

On my end, I'm no longer using it as much as before, so I've stopped contributing for a while.  But when I see PR, I make the effort of reviewing it.  I usually create releases afterwards.

Thanks

**Comment by tombags** [comment]
I've submitted a pull request that changes build-package so it does not transpile the code.  I've been using a private build of olgm build using the change in the pull request for an internal project for a while and I've had no problem using it with OpenLayer 7.x.   The change will likely break compatibility with older versions of some browser that need transpiled code, but we do not use any such browser. 

Sorry for the delay in submitting a fix.  I just received approval to submit the fix from my project.
