### ISSUE TITLE
Installation fails with existing OpenLayers 7.3.0

### ISSUE THREAD

**Issue by nboisteault** [mapgears/ol3-google-maps#344]
Hi,
I'm trying to `npm install olgm` in a directory where there is yet OpenLayers 7.3.0 in the package.json. I get :

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: assets@1.0.0
npm ERR! Found: ol@7.3.0
npm ERR! node_modules/ol
npm ERR!   dev ol@"^7.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ol@"^6.0.0" from olgm@1.7.1
npm ERR! node_modules/olgm
npm ERR!   olgm@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Does anyone know how to fix this? Is this related to https://github.com/mapgears/ol3-google-maps/issues/334?

**Comment by adube** [comment]
Hi @nboisteault

I guess that it is the same kind of issue as #334.  If you're willing to provide a fix for this, I'd gladly review/test it.

Thanks

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
