### ISSUE TITLE
oglm@1.8 : unmet peer ol@7: found 6.15.1

### ISSUE THREAD

**Issue by kinglau66** [mapgears/ol3-google-maps#349]
Thank you for updating the OLGM version to 1.8.0 and specifying that it now requires OpenLayers 7. 
I was wondering, does this mean that OLGM 1.8.0 will no longer support OpenLayers 6, or is OpenLayers 6 merely not recommended? Could you please clarify whether OpenLayers 6 is being abandoned or if there will be issues when using it with OLGM 1.8.0?

**Comment by adube** [comment]
Thanks for reaching out.

I have not tested with OL 6, therefore it is hard for me to state whether it is not supported or not recommended.  It would be safer for me to say "abandoned" and go forward with OL 7.

HTH

**Comment by kinglau66** [comment]
Thanks for your message and clarification. 
I understand your position on OL 6, and will go ahead and upgrade to OL 7 on my side.
