### ISSUE TITLE
Limitation for OverviewMap

### ISSUE THREAD

**Issue by luciman** [mapgears/ol3-google-maps#36]
Hi!

First of all thanks for your nice work.
Do you know if there's a limitation in having Google layer in the Overviewmap?
I could not succeed in doing the above in the Overview examples from ol3 examples.

Thanks a lot!
Lucian

**Comment by adube** [comment]
That's an excellent question!  I have never tried it, but I'm pretty sure it's not currently possible to include an ol3 overview map that contains a google layer (i.e. a `olgm.layer.Google`). That would be a limitation that could be added to `LIMITATIONS.md`.  Would you like to write a PR describing this ?

Before doing so, you could something.  The overview map control is responsible of creating its own map.  It has a `getOverviewMap` getter.  You could bind an other `olgm.OLGoogleMaps` to it.  Try this approach and see what happens.  If you succeed, then it would become a nice use case to add as an example for olgm!

An other less cool solution would be to manually create a second map, either a ol3 or google maps, and bind its view to the main map view.

Let us know how that went.

**Comment by luciman** [comment]
If a new instance of olgm is created for the overview map alike:

`var olGmOvm = new olgm.OLGoogleMaps({map: this.overviewMap.getOverviewMap()});`

It works with both exemples from ol3 exemples.
However, it's not consistent from start ( as sometimes the Google layer in overview is not rendering or has another position).  By switching the baselayer at least once is working fine.

Thank you very much for help and sorry for the late response

**Comment by adube** [comment]
Would you please provide a JSFiddle out of what you're trying to do ?  Or maybe you could create a PR with an example featuring a simple overview map that demonstrates your issue ?

**Comment by samuellapointe** [comment]
I've been able to add an overview map, as seen in #112. To do it, I first activated the olGM instance for the overview map, then I activated the one for the main map. It seems like loading two google maps layers at once doesn't work very well, but loading them sequentially works.
