### ISSUE TITLE
Deal with rotation

### ISSUE THREAD

**Issue by tschaub** [mapgears/ol3-google-maps#4]
It looks like rotation should be disabled if it cannot be set on the Google Map.  Currently, if you use the rotate interaction, panning becomes weird.

Nice work on this!

**Comment by adube** [comment]
That's absolutely right.  The "kinetic" pan is also something not recommended.  I'll add a note in the examples.  Thanks for reporting this.

I think I'll also add a README about those limitations, detailing each one.

**Comment by adube** [comment]
This fix introduces lots of documentation about the rotation and other limitations of the library.  Again, thank you for reporting this.
