### ISSUE TITLE
"fraction" not supported as value for anchorXUnits/anchorYUnits in olx.style.IconOptions

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#40]
anchorXUnits/anchorYUnits value `fraction` seems to be the same as omitting `anchor`, it doesn't do anything. Is the mapping between OpenLayer controls and Google Map controls taking these parameters into consideration?

For example, with an anchor of `[10,10]` and `anchorXUnits`/`anchorXUnits` set to `fraction`, the icon the style is applied to should be placed pretty far above to the left of the coordinate origin, which is the case in "native" layers types like Bing Maps, but in the ol3-google-maps google layer, nothing gets changed:

```
// the anchor is here only applied to non-google layers
var style = new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
  anchor: [10, 10],
  anchorXUnits: 'fraction',
  anchorXUnits: 'fraction',
  src: '/app/images/map_focus.gif'
}))
```

**Comment by adube** [comment]
You're right.  It's not currently supported.  If you're willing to work on a PR, I'd be happy to review it.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
