### ISSUE TITLE
Layering doesn't seem to work when using ol.style.Icon instead of ol.style.Circle

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#41]
jsfiddle where everything works as it should: https://jsfiddle.net/penn/mLrwbtj9/ (note that it takes a while to load due to slow bandwith on the server (orionhub.org) hosting the assets).

What the script does is to paint all the coordinates inside the `coordinates` array as green circles (ol.style.Circle) immediately, then another layer with red circles are painted on top, with a 100ms circle delay of every red circle painted.

Now, if I swap the circle with an icon (`ol.style.Icon`), some of the icons gets painted, some do not, as illustrated in this other jsfiddle: https://jsfiddle.net/penn/8krh3hz4/
The only thing that is changes is that I use `Icon` instead of `Circle`.

Am I doing something wrong, or is this a known or unkown bug?

PS: Here is the example using `ol.style.Icon` and OpenStreetMap instead of ol3-google-maps (it works): https://jsfiddle.net/penn/90va4vws/

**Comment by adube** [comment]
This requires more investigation.

**Comment by samuellapointe** [comment]
Is this still an issue? With the recent updates, it might be fixed...

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
