### ISSUE TITLE
Shift-drag and internet explorer

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#44]
Hi! OpenLayers 3 with ol3-google-maps doesn't seem to work so good in Internet Explorer 10 and 11 when using shift-drag to create "zoom boxes" in the maps. When doing so with ol3-google-maps enabled, stuff around the map are marked, have a look: (IE 10 demo)

https://v.usetapes.com/stuehmgYvX

Any pointers on what might cause this? This is a bummer for my project, as Internet Explorer (sadly) is a required client.

**Comment by adube** [comment]
Hi @fipp !  I just showed this to my colleague @jlap and she already saw this kind of behaviour in an application we develop at Mapgears.  In it, we use ol3, but we do not use ol3-google-maps yet and we were reported the exact same issue.  If we find something, we'll let you know for sure.

**Comment by fipp** [comment]
Thank you @adube!

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
