### ISSUE TITLE
How to access google.maps.map object

### ISSUE THREAD

**Issue by fipp** [mapgears/ol3-google-maps#46]
Hello! In the map I'm maintaining I'm using 3 google map layers, one with ordinary map type, one with satellite map type, and one with hybrid map type. For the record, I'm using ol3-layerswitcher (https://github.com/walkermatt/ol3-layerswitcher) to switch between these.

For the satellite and hybrid map type, Google supports high-res "tilted" imagery for zoom levels over a certain treshold (I believe it is 19), for some areas in the world. This is turned on by default, and I would like to turn it off.

As this (https://developers.google.com/maps/documentation/javascript/maptypes) page says:

_You can disable 45° imagery by calling setTilt(0) on the `Map` object._

Then the question becomes; how do I access the `map` object? Meaning the `google.maps.Map` object behind the OpenLayers 3 google map layer type.

**Comment by adube** [comment]
You could add a `getGMap` method to the `olgm.OLGoogleMaps` and mark it as `@api`.  This should be a fairly simple PR to contribute.  I'd be willing to review it, if you wish to work on this.

**Comment by fipp** [comment]
I've done that now @adube :) Have a look and tell me if I've overlooked something, it was indeed a very easy fix.

**Comment by adube** [comment]
Done in #48.
