### ISSUE TITLE
Concept example not working

### ISSUE THREAD

**Issue by IAmJulianAcosta** [mapgears/ol3-google-maps#49]
Hi! I'm trying concept example but it seems that is not working!

`Failed to load resource: the server responded with a status of 404 (Not Found)
concept.js:142 Uncaught ReferenceError: olgm is not defined`

Line 89 of the HTML: `<script src="/@loader"></script>`

**Comment by adube** [comment]
Hello.  Thanks for reporting this.  The issue has been fixed.  See: http://dev5.mapgears.com/ol3-google-maps/examples/concept.html
You may need to force a refresh of the page to clear your browser cache.
