### ISSUE TITLE
Support WMS layers

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#51]
The task at hand is to support WMS layers in OLGM.  The idea is to let GoogleMaps render those layers instead of OpenLayers for a perfect synchronization while interacting with the map.

The implementation needs to be discussed..

**Comment by jmgomezpoveda** [comment]
Would this feature enable using ol3-google-maps with ol3-cesium?

**Comment by adube** [comment]
I'm not sure.  I don't know ol3-cesium well enough to be able to answer right now.  I'll see if that's possible.

**Comment by samuellapointe** [comment]
WMS Support was added with commit https://github.com/mapgears/ol3-google-maps/commit/2fc99ef7bb8c5faf4c3d02b8072d65902870f327. If issues occur with this implementation, new tickets should be opened.
