### ISSUE TITLE
Support Clusters

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#52]
The purpose of this task is to be able to define cluster styling in OL3 and be able to reproduce the behaviour in GoogleMaps.

At this point, no research nor development has been made towards achieving this and it's not guaranteed  to be even possible.  The first step would be to analyse the possibility to do this and come with an implementation plan.

Opened for discussions.

**Comment by mstenta** [comment]
Is it possible right now to display OL-rendered clusters on top of the Google layers?

**Comment by mstenta** [comment]
> Is it possible right now to display OL-rendered clusters on top of the Google layers?

I discovered that I can use OpenLayers cluster rendering by telling OLGoogleMaps to not watch vector layers:

```js
  // Do not let OLGoogleMaps manage vector layers. It does not support all
  // geometry types, and it does not support clusters.
  const watch = {
    vector: false,
  };

  // Activate Google Maps.
  const olGM = new OLGoogleMaps({ map, watch });
  olGM.activate();
```

**Comment by adube** [comment]
That is currently the only way to achieve clusters with OLGM: by letting OpenLayers render the vector features instead of Google Maps.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
