### ISSUE TITLE
Tile Layer with XYZ  Source Support

### ISSUE THREAD

**Issue by karlfloersch** [mapgears/ol3-google-maps#54]
I'm trying to layer an OpenWeatherMap tileset on top of Google Maps with limited success. I came across this repository and got excited! But I see now that listed in the [limitations](https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md) `ol.layer.Tile` is not supported.

I'm trying to use `ol.source.XYZ` as the source of the layer. What is the timeline for adding Tile support? Also, do you know if this is possible to achieve with the standard OpenLayers API? I've gotten the tiles layered on top using the standard OL API, but I haven't been able to keep Google Maps and OL in sync. (they become off when you scroll around at different zoom levels).

Any help would be greatly appreciated! Also, thank you for maintaining this repository--dealing with these tools can be difficult with such sparse up-to-date documentation. Thank you!

**Comment by adube** [comment]
Hello @karlfloersch.  Thanks a lot for your interest in OL3-Google-Maps !

To answer your questions:

> What is the timeline for adding Tile support?

There's no immediate plan to support tiles sources/layers soon.  We do intent to support WMS sources in the late summer this year, though.

> Also, do you know if this is possible to achieve with the standard OpenLayers API? I've gotten the tiles layered on top using the standard OL API, but I haven't been able to keep Google Maps and OL in sync. (they become off when you scroll around at different zoom levels).

That's the main purpose of OL3-Google-Maps: make Google Maps map take care of rendering the layers for a perfect synchronization while interacting with it.  That means: no.  There isn't a way to perfectly synchronize OL3 and Google Maps altogether (to my knowledge).  If there were, then it would kill the purpose of this lib (and make lots of people happy!)

> Any help would be greatly appreciated! Also, thank you for maintaining this repository--dealing with these tools can be difficult with such sparse up-to-date documentation. Thank you!

Thanks.  If you're willing to work on this feature, you could contribute a pull request and we'd be happy to review.  See the [developing readme](https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md) to setup the development environment and start working on this. How does that sound ?

**Comment by karlfloersch** [comment]
Great! Thank you for your quick and complete response. That makes sense, and now I really understand the positioning of this library. Very useful.

One question though: Is there a way to add a tile layer to Google Maps using their own API? My understanding is that the closest you can get (right now) is using Leaflet with the Google Maps tileset. (https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that) But that's a bit of a hack and against terms of use.

Is it correct that the **only** way to get a Weather Tileset overlay on Google Maps is by expanding this libraries' functionality? There are no existing solutions to this problem? Including using the Google Maps Javascript API?

**Comment by adube** [comment]
@karlfloersch There are ways to render tiles on top of Google Maps, it's just that their API doesn't make it easy.  Here's some examples that do so (all with WMS):
- http://www.gisdoctor.com/v3/openlayers_wms.html
- http://www.gisdoctor.com/v3/wms_single_complete.html
- http://www.sumbera.com/lab/GoogleV3/tiledWMSoverlayGoogleV3.htm

You can look at the source code of these examples to see how they work.  Pretty neat, but kinda complex to understand and implement.

The idea behind the "Support of WMS" (and TMS/TileSets) within OL3-Google-Maps would be to make it as simple as possible, with the use of objects like the `ol.source.ImageWMS` and `ol.source.TileWMS` where you define the url and layers params as minimum config required.  The rest could be taken care of within the code itself to produce the full tile urls.

That's pretty much what I have in mind at least.  I haven't put any efforts into this yet.  Tell us what you think about the general idea.

Oh, and I think that the strategy behind the Leaflet "google" plugins is to put the google maps map behind the leaflet one and synchronize them as much as possible.  It's pretty much the original way the OL3 dev team had in mind, but later decided to remove it completely from their examples to discourage that practice.

**Comment by karlfloersch** [comment]
Awesome answer @adube . That was incredibly helpful. Thank you so much!

I actually asked this question on [StackOverflow](http://stackoverflow.com/questions/35804133/google-maps-javascript-api-with-an-openweathermap-tile-layer-overlay) a second ago, if you copy your answer there I feel it would be really helpful for people looking to do this. I've had so much trouble searching this up, I think the more places to find the info, the better.

**Comment by adube** [comment]
What's the link ?

**Comment by karlfloersch** [comment]
Just added it--sorry about that!

**Comment by samuellapointe** [comment]
XYZ Tile layers are supported since release v0.7 (#86)
