### ISSUE TITLE
Release cycle based on Openlayers versions.

### ISSUE THREAD

**Issue by drupol** [mapgears/ol3-google-maps#55]
Hi,

I'm the maintainer of the [Openlayers module for Drupal](https://www.drupal.org/project/openlayers).
A lot of people are requesting Google Maps layers in the module and I would like to use this library.
Could you please provide regular release of the library and their Openlayers library requirements so I can work on something ?

Thanks.

**Comment by adube** [comment]
Hello @drupol. Thanks for your interest in OL3-Google-Maps!

Sure, I'll try to do a release at the same time that OL3 does. I'll let you know it goes.

**Comment by drupol** [comment]
Cool, thanks ! Could you please release one that works with 3.14.2, so I can already work on this ?

**Comment by adube** [comment]
I should be able to do so.  I have to speak to my boss about this first, but I don't think there should be any problem.  I'll come back to you soon (today).

**Comment by drupol** [comment]
:+1:

**Comment by adube** [comment]
We're okay with making releases more often (one per ol one).  I'll also do the one for 3.14.2 now.  It should be ready today.

I'd like to point out that I only intent to do one release per "major" one, i.e. if OL releases 3.15.0, I'd make one for OLGM, but I wouln't make additional ones for 3.15.1, 3.15.2, etc. as those "bug-fix" releases shouldn't affect the core of OLGM, plus OLGM isn't built with OL anyway.

**Comment by adube** [comment]
I'm having trouble building ol3, which is required to build OLGM.  This task is currently on hold.  See: https://groups.google.com/d/msgid/ol3-dev/6ff82ce9-4bc1-49ac-a28f-f09c9668f3b8%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by drupol** [comment]
:+1:

**Comment by adube** [comment]
The above issue has been fixed in OpenLayers.  Now, I'm facing a new issue: https://groups.google.com/forum/#!topic/ol3-dev/SmN8uZCTVR8

I know that lots of core changes were made between 3.13 and 3.14.  It might take a while to actually do the upgrade.  I'll keep you in touch.

**Comment by adube** [comment]
There you go, v0.4 is out: https://github.com/mapgears/ol3-google-maps/releases/tag/v0.4
