### ISSUE TITLE
text style for Icon feature dont changed after setText()

### ISSUE THREAD

**Issue by antonad** [mapgears/ol3-google-maps#59]
I created icon feature with text style and some text inside style.
Icon and label are on map.
After few second I do so:

```
            var st = marker.getStyle();
            st.getText().setText("");
            marker.setStyle(st);

```

Label on google layer stay the same, but if I choose OSM or MapQuest label disappears

**Comment by adube** [comment]
Indeed, there's no herald currently watching text being changed within a style. Can you try setting a new style object instead of setting the text ?  It could be a good alternative. Otherwise, if you're willing to work on a PR to fix this, feel free to contribute.

Thanks!

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
