### ISSUE TITLE
Heat map

### ISSUE THREAD

**Issue by yungfei1989** [mapgears/ol3-google-maps#61]
Hi I use your google, why it return error when I use heat map? how to fix this error..This error not found when I disable google map...thanks

**Comment by adube** [comment]
Hi.  First, thanks for your interest in OL3-Google-Maps.

Now, about your issue.  You'll need to give more information about your issue.  What is it exactly that your are trying to do ?  If you could share snippets of your code or even better create a JSFiddle out of it that demonstrates your issue ?  What is the error message ?  Please, give as much info as you can.

Help us help you!

Best regards,

Alexandre

**Comment by yungfei1989** [comment]
Hi Adube, I want to draw heatmap in google layer...my code : 

```
MapOL3.prototype._DrawHeatMap = function (features) {
        var source = new ol.source.Vector({
            features: features
        });

        self._olHeatMapLayers = new ol.layer.Heatmap({
            source: source,
            blur: parseInt(30, 10),
            radius: parseInt(10, 10)
        });

        self._olHeatMapLayers.getSource().on('addfeature', function (event) {
            event.feature.set('weight', 30);
        });


        this._olHeatMapLayers.setZIndex(0)
        this._olMap.addLayer(self._olHeatMapLayers);        
    }
```

when I use google map there is error in ol.js. Openlayer can't get the feature in heatmap layer.

ol.layer.Heatmap = function(opt_options) {
}

```
var weight = goog.isDef(options.weight) ? options.weight : 'weight';
  var weightFunction;
  if (goog.isString(weight)) {
    weightFunction = function(feature) {
      return feature.get(weight);
    };
  } else {
    weightFunction = weight;
  }
```

feature is undefined and all of my code after it not running well..How the heatmap layer function can detect feature..this case only happen when I include google map use your JS...Please help me to fix it...

thanks..

**Comment by adube** [comment]
Okay, so `ol.layer.Heatmap` inherits from `ol.layer.Vector`, therefore OLGM tries to draw it in Google Maps.  But that was never actually tested and I don't think that heatmap layers are currently supported out of the box in OLGM.  This is something that would require work.

If you're willing to work on this feature, feel free to contribute a PR.

If you're willing to fund this feature, that could also be a possibility.  If you prefer this, you can ask at: info at mapgears.com.

Thanks!

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
