### ISSUE TITLE
Blackscreen when using OL3 FullScreen control with OLGM

### ISSUE THREAD

**Issue by IsmayilAqazade** [mapgears/ol3-google-maps#65]

**Comment by adube** [comment]
Could you please provide more details to this issue ?

**Comment by IsmayilAqazade** [comment]
I solved this issue. Problem was google script url line .
I have another problem with ol3gm.
I added fullsccreen control to map.But when i click fullscreen then don't show map on windows.Windows fullscreen but it shows black screen ,like this photo:
![ol3](https://cloud.githubusercontent.com/assets/5353956/14386858/71aa3384-fd5b-11e5-84c7-8605314b2e57.png)

**Comment by adube** [comment]
Could you please provide a live example, in a JSFiddle (maybe) where this issue is demonstrated ?  Also, if you're willing to work on a PR it would be nice.

**Comment by IsmayilAqazade** [comment]
I solved problem this way : I have added my css file this code : `.map {
  width: 100%;
}
`
if I don't add it then I don't show another layers with fullscreen.

**Comment by adube** [comment]
Glad to hear you were able to solve your issue.  I'm closing this ticket.
