### ISSUE TITLE
search with Google place lib 

### ISSUE THREAD

**Issue by IsmayilAqazade** [mapgears/ol3-google-maps#67]
How to do google place autocomplit with this lib?

**Comment by adube** [comment]
The purpose of OLGM is to make it possible to use the OpenLayers API to build a map in which you can have Google Maps layers.

You can get the Google Maps map object using the `olgm.OLGoogleMaps#getGoogleMapsMap` method and do whatever is possible to do using native Google Maps API with it.

If you would be able to create your web mapping application with only the Google Maps API, it is recommended to use it only.

Does that answer your question ?

**Comment by IsmayilAqazade** [comment]
Could you please provide a live example, in a JSFiddle ?

**Comment by adube** [comment]
The following example demonstrates how to use the `olgm.OLGoogleMaps#getGoogleMapsMap` method to use the traffic layer feature of Google Maps along with OLGM: http://dev5.mapgears.com/ol3-google-maps/examples/traffic.html

See how it's done: http://dev5.mapgears.com/ol3-google-maps/examples/traffic.js

Does that answer your question ?
