### ISSUE TITLE
Create an example with vector layers unmanaged

### ISSUE THREAD

**Issue by adube** [mapgears/ol3-google-maps#68]
OLGM can be configured to not "manage" vector layers, i.e. instead of making them render in Google Maps directly, they stay in OpenLayers.

This has the down-side of making the animation while zoomin in/out not synchronized between OL and GM, but for some users it may still be better than nothing.

The task at hand is to create an example featuring a vector layer not managed by OLGM.  In it, we could put some interesting displays of features that are cool in OL, but not yet managed in OLGM, such as clusters.

**Comment by samuellapointe** [comment]
PR #111 includes an example with unmanaged tile layers.
