### ISSUE TITLE
Not succeeding in using ol3-google-maps

### ISSUE THREAD

**Issue by glemaitre1** [mapgears/ol3-google-maps#83]
Hi everyone.

I'm trying to get a map using your library 0.6 that contain OL3, but i just cant get it worked.
Not sure this is the place to ask for help, but i'll only know it by trying si here's my problem.
I'm giving the sources to my page this way: 

> link rel="stylesheet" href="/jscript/OpenLayers-3.16/css/ol.css" type="text/css"/> 
>    link rel="stylesheet" href="/jscript/ol3-google-map/css/ol3gm.css" type="text/css"/> 
>    script src="myapikey"> /script>
>    script src="/jscript/ol3-google-map/src/ol3googlemaps.js"> /script>

I load a js script of mine that countain the initialisation and stuff in order to create the map after my "div id='map'> /div>" to be sure there is no loading issue but still i got the following error when he first tries to create the map:
'ReferenceError: ol is not defined'.

Could anyone help me please?
Cheers.

EDIT: Removed all the '<' because the editor doesnt seem to like it.

**Comment by samuellapointe** [comment]
This is how I usually place my scripts in the html file:

```
<script type="text/javascript" src="myApiKey"></script>
<script src="ol3gm.js"></script>
<script src="myScript.js"></script>
```

`myScript.js` contains the code that creates the map. All these scripts are at the end of the file, just before the closing `</body>` tag. If you place your scripts in the same order, does it still happen?

**Comment by glemaitre1** [comment]
Yeah i'm putting them in the same order. I just tried with src/ol3googlemaps.js as well as src/ol3gm.js and build/build.js because i'm not sure which one i'm supposed to use.
But i just saw that i got one of the following error (must be tired to not have seen it last time):

`goog is not defined
or require is not defined`

depending on which of the three js i'm using. But isnt ol3-google-maps including goog as well as ol3?

Thanks for your time, that's very nice of you to help me!

**Comment by samuellapointe** [comment]
The files in the `src` folder aren't compiled, they only include a small part of the code each and without ol3. You need to use the compiled file, which contains all of the code as well as ol3. On the [release page](https://github.com/mapgears/ol3-google-maps/releases/tag/v0.6), there's a link to the compiled version: https://github.com/mapgears/ol3-google-maps/releases/download/v0.6/ol3-google-maps-v0.6.zip

You can also compile it yourself with the instructions on [this page](https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md), but that isn't necessary unless you want to use the very latest version.

I hope this helps!

**Comment by glemaitre1** [comment]
Well i knew i was doing something horribly wrong somewhere.. you found it.
Thank you very much for your help, i was looking for my mistakes for hours now.
Sorry about the newbie threat and thanks for your time you lovely fellow!

**Comment by samuellapointe** [comment]
No problem, I'm glad it works now!
