### ISSUE TITLE
Windows build support

### ISSUE THREAD

**Issue by sindrma** [mapgears/ol3-google-maps#93]
Hi!
I am currently working in a software firm which greatly appreciates ol3-google-maps. However, we had problems building on Windows. We fixed it by following a proposed solution discussed [here](https://www.bountysource.com/issues/2283601-building-ol-3-since-beta-5-on-windows?utm_campaign=plugin&utm_content=tracker%2F79013&utm_medium=issues&utm_source=github), which have been integrated into OL3. 

If wanted, we would gladly submit a PR to fix the issue, as it may be of interest to future developers.

**Comment by adube** [comment]
I like the sound of that!  Please, feel free to contribute a PR and I'll gladly review it.

**Comment by adube** [comment]
FYI, the build script now includes the OpenLayers lib along with OLGM in the minimized script files.  Make sure you try with the latest version (0.6) or with the master branch.

**Comment by samuellapointe** [comment]
Fixed with PR #95
